### ISSUE TITLE
Java API for Onyx

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#1]
As of release 0.3.0, Clojure is the only supported language for Onyx. Java users can use the APIs that Clojure offers to tap some of the Onyx functionality, but this becomes problematic for areas such as lifecycle extensions that rely on implementations of multimethods.

Furthermore, EDN isn't the friendliest cross-language data format to send catalogs and workflows through. Part of this issue should explore options that Java users have on this front.

**Comment by aaelony** [comment]
We have few Clojure people, but many Java devs. Some on our team have raised this issue as well, and this may become an issue.

**Comment by MichaelDrogalis** [comment]
A Java API is low on our priority list. Two viable paths to its completion are someone stepping up to work on this one with some guidance, or fund it's development.

**Comment by MichaelDrogalis** [comment]
Finally got this one done. Thanks community! https://github.com/onyx-platform/onyx-java
