### ISSUE TITLE
Make an application template

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#109]
Ship a template with 0.6 to get started quicker.

**Comment by lbradstreet** [comment]
Definitely agree with this one and if we can push users towards component in it, all the better. 

I think it's quite a necessary part of the puzzle with respect to getting a good Onyx workflow happening.

**Comment by MichaelDrogalis** [comment]
Another thing that we ought to include here are CloudFormation and Mesos/Marathon scripts. Both of these are excellent ways that are both proven to get started easily.

**Comment by MichaelDrogalis** [comment]
Finished. See https://github.com/onyx-platform/onyx-template.
