### ISSUE TITLE
Create a nice reusable test helpers for end user use

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#112]
I'm thinking something that starts up the right amount of peers for the number of tasks, pushes through the data that you want on the particular input tasks that you want, and then checks the output tasks for the expected results.

So, maybe supply a catalog, a workflow, and a map containing the data to put into the input tasks, and return a map of the data that is received by the output tasks.

This functionality would depend on the input and output tasks using core async, so there would be some limitations. 

We could probably provide another helper function to mess with the catalog to convert any non-core async input/output tasks to core async. Not so sure about that part though.

The testing strategly would be like this, but would need to remove the use of defs and a lot of the boilerplate, and making it so a user can easily incorporate it into a TDD like workflow (if that floats their boat):

https://github.com/MichaelDrogalis/onyx/blob/0.6.x/test/onyx/peer/min_peers_test.clj

**Comment by MichaelDrogalis** [comment]
Much desired.

**Comment by MichaelDrogalis** [comment]
I think this is covered quite well in the application template. Closing for now, unless you'd like to reopen to add more.

**Comment by lbradstreet** [comment]
The component you used plus binding inputs is pretty much exactly what I wanted plus we have the helper env for the our more stateful tests
