### ISSUE TITLE
Extend group-by-key in the catalog entry for composites

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#118]
I see a good use case for wanting to group by multiple keys, as in `:onyx/group-by-key [:key-1 :key-2]`

**Comment by gardnervickers** [comment]
We should be able to just `(juxt :foo :bar)`. Not entirely sure where to put this.

**Comment by MichaelDrogalis** [comment]
I think it would fit somewhere in here. https://github.com/onyx-platform/onyx/blob/master/src/onyx/peer/task_lifecycle.clj#L94-99 :)
