### ISSUE TITLE
Compile docs to GitBook

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#119]
Should be a pretty easy task if someone wants to take a shot at putting the User Guide under GitBook.

**Comment by danielcompton** [comment]
I sent you an invite for GitBook, someone with commit access (presumably you) will need to create the book, then I can work on it.

**Comment by MichaelDrogalis** [comment]
@danielcompton I created the book and added you as a collaborator with admin rights. Thanks for helping!

**Comment by MichaelDrogalis** [comment]
Fixed in PR #226.
