### ISSUE TITLE
Log message if not enough peers are available for a job

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#133]
This seems to be the number 1 gotcha to Onyx.

**Comment by davidrupp** [comment]
You might also consider updating example code to define peers based on some function of the catalog size; e.g., (def v-peers (onyx.api/start-peers (count catalog) peer-group)). That would make the connection explicit for those learning from the examples.

**Comment by MichaelDrogalis** [comment]
Ah - that's a very good idea. Thanks!

**Comment by lbradstreet** [comment]
I'm using a similar idea in the test helper I'm writing. If the number of peers is less than (count (distinct (flatten workflow))) an error is thrown.

**Comment by davidrupp** [comment]
Another thought: decorate the workflow definition with the desired parallelism per task (default: 1) and just let Onyx calculate the number of peers.

**Comment by MichaelDrogalis** [comment]
Done on master.
