### ISSUE TITLE
Documentation dedicated to timeouts

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#138]
We need documentation for every place in the codebase that has a timeout, what it means, and how to adjust it. These are critical for operating in a production setting.

**Comment by lbradstreet** [comment]
As a part of this, lets put all the default timeout constants in a single file which can be referenced from the various places they're used.

**Comment by MichaelDrogalis** [comment]
Excellent idea!

**Comment by MichaelDrogalis** [comment]
Done in master.
