### ISSUE TITLE
Document aeron property options

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#140]
This should include some of the aeron properties that allow buffer sizes / mtus, etc, to be changed. These are necessary in order to transfer large segments.

**Comment by lbradstreet** [comment]
This is not a blocker as we may not release aeron with 0.6.0.

**Comment by MichaelDrogalis** [comment]
Moving to 0.7.0 milestone.

**Comment by lbradstreet** [comment]
I'll get this done shortly. It'll mostly be a pointer to the Aeron documents as I don't have many good suggestions yet other than what to look out for when you hit overruns e.g. messages over a certain size will fail.

**Comment by lbradstreet** [comment]
Closed by #267
