### ISSUE TITLE
ZeroMQ messaging implementation

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#146]
This would be interesting as a performance experiment.

**Comment by lbradstreet** [comment]
Does this give us any interesting properties in comparison to our netty/aeron implementations? I was hoping it was a queue with similar properties to HornetQ, which might be useful for some use cases. If it's going to be similar to our existing implementations then I think we can hold off on this for a while.

**Comment by MichaelDrogalis** [comment]
It's mostly for feature matching Storm - there's nothing special here, certainly not a blocker.

**Comment by MichaelDrogalis** [comment]
Not interested in this anymore.
