### ISSUE TITLE
Revisit replay interval

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#147]
See Gitter discussion of replay intervals vs batch timeouts.

**Comment by MichaelDrogalis** [comment]
I took some time to think about this one, and nothing is jumping out at me that's obviously wrong.

**Comment by lbradstreet** [comment]
I haven't thing anything pop up here recently either. I think Onyx just used to be slower on dag-test and messages were getting replayed as they should be.
