### ISSUE TITLE
PeerLink resource management strategy

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#151]
A long running job will likely end up with a connection from every peer to every other peer, since acking is done at random nodes. We should consider a strategy to periodically reap these. 

In addition, I don't think we close these connections as vpeers leave the cluster.

**Comment by MichaelDrogalis** [comment]
I sort of had this in the back of my mind. Thanks for calling attention to it. Another thing that I'm wondering about are tasks that have *many* immediate downstream peers. We might want to have a parameter to limit how many peer connections it can open in the first place.

**Comment by MichaelDrogalis** [comment]
On eeeet.

**Comment by MichaelDrogalis** [comment]
Pull requested opened.

**Comment by MichaelDrogalis** [comment]
Merged into master.
