### ISSUE TITLE
onyx.peer.dag-test should be able to handle a greater volume of seed messages

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#152]
Netty seems fine, so this is probably an Aeron problem.

Currently things go awry with 100K messages sent to 3 tasks. Obviously it's a fairly complex test given the number of peers and the way the messages split but I think we should be able to handle this without fail on a 4 core machine with 16G RAM

**Comment by lbradstreet** [comment]
Netty seems to churn at around 500K messages. I think a lot of this is just optimisation work, but there's probably some work to be done with backpressure.

**Comment by MichaelDrogalis** [comment]
Yeah, we definitely have high-volume testing up on our plate for both single and multinode clusters. Good to have this on the radar.

**Comment by lbradstreet** [comment]
I'll take this one. I think we can improve performance here by reusing buffers and just updating the acks when sending to multiple tasks.

**Comment by MichaelDrogalis** [comment]
I'm comfortable to close this one if you are.

**Comment by lbradstreet** [comment]
With core.async fixes this runs fine. Backpressure improvements required for high max-pending will be tracked in #197
