### ISSUE TITLE
Look into Aeron multicasting

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#158]
For tasks where flow conditions are not used, it may be beneficial to look into Aeron's multicasting type feature. I imagine this could improve send performance substantially.

Since messaging isn't currently our bottleneck, it may not be worth looking at yet.

Separate idea, when sending messages, supply all peer links so serialisation to buffers are only performed once.

**Comment by lbradstreet** [comment]
The main problem with both of these is the ack-vals. There may be clever ways around this though. I'm yet to do hardcore profiling but the serialisation cost is a pretty big deal.

**Comment by lbradstreet** [comment]
With netty I think the solution is to send all the segments without acks and then write out the acks in the next message (message order is guaranteed by TCP, and we can write, write, flush). We will probably need to retain the reused bufs n-1 times. Anyway, just an idea for the future.

**Comment by lbradstreet** [comment]
For aeron, aeron copies on offer, so we can reuse the buf - all we need to do is modify the ack vals

**Comment by lbradstreet** [comment]
For netty we can use two byte bufs. One without the acks, one with, then send a composite byte buf

**Comment by MichaelDrogalis** [comment]
@lbradstreet We can close this one, correct?

**Comment by lbradstreet** [comment]
We haven't made any movement on this one, but I can't see us doing it any time so I'm going to close it.
