### ISSUE TITLE
Per-task nippy data compression

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#179]
By compression I mean snappy or deflate (zip) compression. This is supported by nippy but has to be turned on / off, and Onyx turns it off by default.

Small segments are expensive to compress and hurt latency, but for tasks where large amount of data is sent, compression could be essential. Thus it may be better to allow for compression to be selected per task as part of the catalog entry.

**Comment by MichaelDrogalis** [comment]
Hey @lbradstreet. @tvanhens is looking to get involved again and wants to learn the Onyx internals. Think this would be a good larger ticket for him to work on?

**Comment by lbradstreet** [comment]
Yep, I definitely agree this would be a good one.

**Comment by gardnervickers** [comment]
I understand why this is a horrible idea for a streaming data platform, but in PHCI/HIPPA constrained environments there are mandates on in-flight data. It might be nice to allow users to specify a Nippy encryption method too.

**Comment by MichaelDrogalis** [comment]
Nippy has encryption built in. You can use the pluggable compress/decompress functions on the peer config to do that. :)

**Comment by lbradstreet** [comment]
I'm back onto this one tonight. I'll write up my requirements and the general way I think it should be implemented.

**Comment by lbradstreet** [comment]
Currently compression works by using a default compress and decompress function. These are defined here:
https://github.com/onyx-platform/onyx/blob/master/src/onyx/compression/nippy.clj#L4

These functions can currently be overridden by via the peer-opts:
https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/peer-config.md#onyxmessagingdecompress-fn

We would like to change the configuration to split the compress-fn and decompress-fn from their options e.g. "{:compressor nil}" here https://github.com/onyx-platform/onyx/blob/master/src/onyx/compression/nippy.clj#L5.

That way either the (de)compressor options or the (de)compressor fn, or both, can be overridden. 

When the peer-group starts up, the compress-fn is either the nippy based compress/decompress or the fns supplied via the peer-opts.
https://github.com/onyx-platform/onyx/blob/master/src/onyx/messaging/aeron.clj#L229
This should be extended to also supply the arguments to the compressor / decompressor fns, defaulting to the options currently used in https://github.com/onyx-platform/onyx/blob/master/src/onyx/compression/nippy.clj#L5. This will also have to be done for the netty implementation.

Once compressor/decompressor options are able to be supplied via the peer opts, the next step is to allow custom compressor options to be supplied via the task. The key here is to resolve the options from the task map when the task starts up (see https://github.com/onyx-platform/onyx/blob/develop/src/onyx/peer/task_lifecycle.clj#L632), and then supply the options to the messaging layer (see https://github.com/onyx-platform/onyx/blob/develop/src/onyx/peer/function.clj#L37). You may need to change the send-messages signature to make this task independent. I see no clean way to make decompressor options task independent. Thankfully, nippy depends on writing the compressor options in the header - hopefully this is true of other compressors too.

**Comment by lbradstreet** [comment]
So, there are a few problems with this approach. The first is that nippy compressor opts aren't necessarily serializable. See https://github.com/ptaoussanis/nippy/blob/master/test/taoensso/nippy/tests/main.clj#L27. We may need to allow the opts to be looked resolved via a keyword (as with lifecycle maps).

The second problem is that decompression will also require the next task to be supplied with similar opts. My understanding of nippy was incorrect (using no compressor seems to work fine). This may make per-task compressor opts quite annoying to implement. What we've got might be good enough.

**Comment by lbradstreet** [comment]
I haven't figured out a way around this one. I think leaving compression configurable via the peer-opts is the best approach for now.
