### ISSUE TITLE
Fix upstream reflection warnings in zookeeper-clj

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#184]
I don't like our lib being a source of reflection warnings in other people's code, especially for performance sensitive applications like ours. This should help very very slightly with log performance too.

**Comment by MichaelDrogalis** [comment]
I have commit rights on that project - can take care of that with a patch when we have one.

**Comment by lbradstreet** [comment]
Roger that.

**Comment by lbradstreet** [comment]
We use our own curator implementation now which is completely reflection warning free.
