### ISSUE TITLE
Rename lifecycle events

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#186]
Thinking 
`:pre-batch` / `:post-batch` 
`:pre-initialise-task` /  `:pre-shutdown-task`? (I'll need to check on whether they're actually pre-initialise and pre-shutdown)

**Comment by MichaelDrogalis** [comment]
Going with `:lifecycle/before-task-start`, `:lifecycle/before-batch`, `:lifecycle/after-batch` `:lifecycle/after-task-end`.

**Comment by MichaelDrogalis** [comment]
Fixed on master, docs updated.
