### ISSUE TITLE
Virtual peer should be rebooted after ZK connection is lost

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#189]
Sometimes the vpeer's connection to ZK will timeout. The vpeer should be restarted after this occurs.

I'm not sure where the best place for this is. The first problem is that we need some kind of connection management. The client will try to reconnect but after it finally times out I think it's dead for good. At this point we should probably signal the virtual peer to restart.

**Comment by lbradstreet** [comment]
Is putting a value on restart-ch when certain exceptions are caught in https://github.com/onyx-platform/onyx/blob/0.6.x/src/onyx/peer/virtual_peer.clj#L52 what you had in mind for this issue?

**Comment by MichaelDrogalis** [comment]
Yep.

**Comment by lbradstreet** [comment]
Tracking work in https://github.com/onyx-platform/onyx/tree/fix/restart-vpeer. It may be a bad idea to allow restart on SessionExpiredException. Maybe it'll be better in production, but it might be confusing when users are testing and forget to shutdown-peer.

The next problem I see, is that if the node is temporarily unable to connect to ZK, restarts, and is still unable to connect when the component is started here https://github.com/onyx-platform/onyx/blob/b35b231dfa0bcd7dbee3f0fd8c0868dd62c6e8fe/src/onyx/api.clj#L233, then I believe it'll give up. I think we may need to catch certain exceptions in start and put another value on restart-ch (or some other similar solution).

**Comment by lbradstreet** [comment]
You could try a restart in here: https://github.com/onyx-platform/onyx/blob/b35b231dfa0bcd7dbee3f0fd8c0868dd62c6e8fe/src/onyx/peer/virtual_peer.clj#L106

One other problem is that a connection loss might mean that a completely different exception will be hit when chunks are written when the peer starts up (unable to connect etc). I think the peers should retry for these exceptions too.

**Comment by lbradstreet** [comment]
I've decided that we should just bite the bullet and use curator. I've started writing some of the functions that we need. It shouldn't be too hard.

**Comment by MichaelDrogalis** [comment]
That sounds good to me.

**Comment by lbradstreet** [comment]
Closed, as we now use curator to handle these issues. See #206
