### ISSUE TITLE
Run without Zookeeper?

### ISSUE THREAD

**Issue by hansgru** [onyx-platform/onyx#196]
Is it possible to run Onyx without zookeeper?
If yes, than how? (even the samples and the templates are using it)

For many usage scenarios (I would say most that I've encountered so far), a single instance should be more than enough for all the data, so there's no need to distribute the processing.

Thank you.

**Comment by MichaelDrogalis** [comment]
It's not possible to run Onyx without ZooKeeper, no. Onyx is meant for distributed data processing. If you can get use out of it by running it as a single node with ZooKeeper in memory without fault tolerance requirements, that's great - but it's not what we're targeting as the primary use case.

**Comment by hansgru** [comment]
> Onyx is meant for distributed data processing.

Sorry, but I don't really get it: I need a distributed processing only when a single node can't handle the load (I mean even for a few hundred GB of data).

So far I've seldom encountered such scenarios and if there was, than the implementation was inefficient, and after performance tuning, mostly there was no need for extra nodes.

**Comment by MichaelDrogalis** [comment]
The use cases that we're looking at are for when you truly do need more than one machine. You can run Onyx as a single node. Is there a particular point in the design that makes running ZooKeeper in memory problematic for your scenario?

**Comment by lbradstreet** [comment]
It's worth noting that the overhead of coordinating the peers on your local laptop via the in memory ZooKeeper instance is quite small. Once your job is up and running the peers will burn very little CPU coordinating. It sounds like in memory ZooKeeper will fit your local processing purposes quite handily. 

For such use cases, you may wish to evaluate the core.async messaging layer. This messaging layer is only available when running locally, and reduces the peer messaging overhead as no serialisation is performed - this is far more beneficial than running Onyx without ZooKeeper could ever be.

**Comment by hansgru** [comment]
Thank you for your explanations.

> Is there a particular point in the design that makes running ZooKeeper in memory problematic for your scenario?

1. It makes the getting started more complicated, one more thing the users need to know and learn and maybe never need.

2. I requires at least a free port.

3. If I'm required to run on the same machine more instances that have nothing to do with each other, no coordination required (since physical hardware is quite powerful compared to virtual cloud instances), than it seems that I need to choose even more free ports?

So basically it's an overhead that I can't to see it's need until the scenarios get very complicated, so at a first sight it looks like unnecessary complexity. Of course, I can understand that Onyx depends completely on ZooKeeper so than it's a requirement, not a choice.

> The use cases that we're looking at are for when you truly do need more than one machine.

I worked with quite a few companies (no startups and not in Silicon Valley :) ), and I yet have to see one that has TB of "real" data to process (I'm not talking about weblogs or crawling data since they are just too verbose and this problem is already solved), so that a single machine couldn't handle it.  


> It sounds like in memory ZooKeeper will fit your local processing purposes quite handily. 

OK, but what does it do? If I have a single instance with no coordination required? From the "features" listed on ZooKeeper site, I found none that one might require doing "non-distributed" data processing :).

**Comment by lbradstreet** [comment]
> So basically it's an overhead that I can't to see it's need until the scenarios get very complicated, so at a first sight it looks like unnecessary complexity. Of course, I can understand that Onyx depends 
completely on ZooKeeper so than it's a requirement, not a choice.

Onyx revolves around the concept of workflows which must contain two or more tasks. Onyx's design is such that each of these tasks must run on a "virtual peer" (which may or may not be co-located on the same peer). These virtual peers coordinate a log stored in ZooKeeper.

>> It sounds like in memory ZooKeeper will fit your local processing purposes quite handily. 

>OK, but what does it do? If I have a single instance with no coordination required? From the "features" listed on ZooKeeper site, I found none that one might require doing "non-distributed" data processing :).

It is certainly possible to replace ZooKeeper with a local shared log for this use case, however the advantages compared to using an in memory instance are not worth the engineering effort given the use cases we are aiming at. The in-memory ZooKeeper works just fine.

**Comment by hansgru** [comment]
> Onyx revolves around the concept of workflows which must contain two or more tasks. Onyx's design is such that each of these tasks must run on a "virtual peer" (which may or may not be co-located on the same peer). These virtual peers coordinate a log stored in ZooKeeper.

Now I get it :) ! Thank you for the detailed explanation. 

I wasn't expecting this approach, as in most ETL or processing systems I've used, the "workflow"  is what you describe as "task" in Onyx :).

**Comment by lbradstreet** [comment]
If you would like to read about the design further, please have look at https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/internal-design.md.

**Comment by MichaelDrogalis** [comment]
A task is not not analogous to a workflow in other systems. You can read about [the terminology](https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/concepts.md) in the docs.

I'm not interested in pursuing this specific point about ZooKeeper further. It's completely essential to how Onyx has been architected, and the peers couldn't function without a massive overhaul to support removing it. If you'll only ever need a single node, I recommend using core.async directly and avoiding the overhead of using Onyx entirely. I appreciate your input.

**Comment by hansgru** [comment]
> It's completely essential to how Onyx has been architected,

Got it. Thank you very much for the many details and your support !
