### ISSUE TITLE
ack-daemon-timeout should be the max of all input task pending-timeouts

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#210]
By setting ack-daemon-timout to the maximum of all input task timeouts, you ensure that a message will be retried before it is cleared (or at least very close to, given some clock skew)

**Comment by MichaelDrogalis** [comment]
Since the acking daemon starts before the virtual peer, and are agnostic to jobs, they can't access the catalog of the task that the virtual peer is currently executing. I took the opposite approach to get this issue done: assert that the pending timeout is less than the ack timeout. See PR #212

**Comment by lbradstreet** [comment]
Closed by #212
