### ISSUE TITLE
take-segments! and await-job-completion should take timeouts

### ISSUE THREAD

**Issue by leathekd** [onyx-platform/onyx#219]
Currently they'll wait forever for data that may never come.

**Comment by leathekd** [comment]
Looks like both return some value (await-job-completion appears to return `true`) so they could instead return nil if they timeout.  Another alternative, I guess, would be a TimeoutException.

**Comment by MichaelDrogalis** [comment]
`nil` would be acceptable.

**Comment by MichaelDrogalis** [comment]
Easy one to pick off for 0.7.0. Will take it.

**Comment by MichaelDrogalis** [comment]
Reserved as an issue for Bridget and Nola.

**Comment by gardnervickers** [comment]
For `await-job-completion` I'm not sure the argument ordering. It would be nice to be able to specify quasi-builder-style `(await-job-completion peer-config job-id :monitoring-config {:monitoring :no-op} :timeout 100)` 

But for now I decided to keep it consistent with the rest of onyx.

**Comment by MichaelDrogalis** [comment]
Merged this one in as a patch, then changed the signature to used opts as discussed. Thanks for everyone's hard work and thoughts on this.
