### ISSUE TITLE
Build out benchmark suite

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#228]
We need to bench (and track) more workflow types than we are currently doing in onyx-benchmark.

Off the top of my head:
Tasks that return multiple segments.
Grouping workflows
Flow conditions
Workflows with high branching factors A -> B,C,D,E -> F, rather than the current A->B->C->D->F.

Statistics to be tracked:
* Fully acked latency
* Througput

**Comment by lbradstreet** [comment]
Ideally this will be run in an automated way (probably on my machine). For many of these benchmarks I think it's enough to initially run them locally.

**Comment by MichaelDrogalis** [comment]
I added a workload profile for each of these in the new Ansible branch of the onyx-benchmark repo.
