### ISSUE TITLE
:onyx/restartable-fn

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#249]
In lieu of a static list of restartable-exceptions (see https://github.com/onyx-platform/onyx/blob/master/src/onyx/peer/task_lifecycle.clj#L20), I think it might be worth parameterizing a function that checks whether the exception returned by a task is restartable.

For example, I have a case where I want to test fault tolerance of the datomic plugin and would love to return a clojure.lang.ExceptionInfo with `{:restartable? true}`, and it would be trivial to add a handler for this if it was parameterizable in the input task. I'm thinking something like:

`:onyx/restartable-fn :onyx.plugin.datomic-input-test/restartable?`
where 
```clojure
(defn restartable? [e]
   (and (= (type e) clojure.lang.ExceptionInfo)
           (:restartable? (ex-info e)))
```

Plugin authors could supply catalog entries that include a restartable? fn that allows for vpeers to be restarted under allowable conditions.

cc/@MichaelDrogalis

**Comment by lbradstreet** [comment]
Ideally I'd like this feature to be included in 0.7.0. I'm going to add fault tolerance testing to all the plugins as I port them to 0.7.0.

**Comment by MichaelDrogalis** [comment]
:+1: Good idea!

**Comment by lbradstreet** [comment]
Any thoughts on the name? I'm inclined towards `:onyx/restartable?-fn`, though the question mark before the hyphen is a little odd.

**Comment by MichaelDrogalis** [comment]
Yeah, not a fan of that name. I'd be okay with `:onyx-supress-fn` or `:onyx/restart-fn`. Also, could do `:onyx/restartable? true` with `:onyx/restart-fn`. That opens up more extensibility in the future.

**Comment by MichaelDrogalis** [comment]
Patch merged into develop.
