### ISSUE TITLE
can't-find-task error message is unhelpful

### ISSUE THREAD

**Issue by mccraigmccraig** [onyx-platform/onyx#256]
https://github.com/onyx-platform/onyx/blob/master/src/onyx/static/planning.clj#L11

gives "false" as the error message, instead of the unfound task name

**Comment by lbradstreet** [comment]
Did you see this in practice? I think any catalog/workflow that has this issue would fail validation.

**Comment by mccraigmccraig** [comment]
yes, i saw it when i first tried to submit a job : my catalog is a half-constructed mess atm... it's no biggie, but it would have been helpful to have a more specific error message

**Comment by lbradstreet** [comment]
Okay, thanks for the report. We definitely want to keep our errors helpful.

**Comment by MichaelDrogalis** [comment]
I fixed this in the LambdaJam template. I'll prioritize #247 to fix this and other issues.

**Comment by MichaelDrogalis** [comment]
This is fixed in [develop](https://github.com/onyx-platform/onyx/blob/develop/src/onyx/static/planning.clj#L11-16).
