### ISSUE TITLE
Cheat Sheet

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#258]
It'd be useful to have a quick-reference of everything you'd want to know when working with Onyx.

**Comment by gardnervickers** [comment]
One thing I always forget is what gets merged into the lifecycle map and the event map, and at what time. 

Also the different ways you can parameterize functions.

**Comment by MichaelDrogalis** [comment]
Time to get this one going. Let's take all the information under:

- https://github.com/onyx-platform/onyx/blob/develop/doc/user-guide/information-model.md
- https://github.com/onyx-platform/onyx/blob/develop/doc/user-guide/peer-config.md

And get some interactive ClojureScript going on here. This should build off of a data structure similiar to [this](https://gist.github.com/MichaelDrogalis/2a18cbb14e133f66518d). The next step will be automatic schema generation - but let's get some basic, interactive docs down.

**Comment by MichaelDrogalis** [comment]
I'll continue to update that Gist with more information as we go. Really what we're looking for help with here is the visualization - not looking to pull anyone into documentation grunt work.

**Comment by giorgio-v** [comment]
Just to know if I’m on the right track: are you thinking about using the documentation to generate the data structure in the gist or the other way around? Dumb question, I know, but just to start somewhere.

**Comment by MichaelDrogalis** [comment]
@giorgio-v Good question! We'd start with the data structure and generate the documentation.

**Comment by giorgio-v** [comment]
How do deal with the document structure? Do you use some kind of template? More importantly, though, what kind of interaction are you thinking about?

**Comment by MichaelDrogalis** [comment]
Just throwing out an idea, I think we'll have a better idea once we start to see something:

I was thinking of a page with tabs for each logical grouping of information in Onyx. For example, we'd start with a tab for the Catalog. The catalog has a specification for what is allowed to be belong in the keys for each entry. It would be cool to list all the possible keys, and when you click on it, you get a blurb telling you what the key is, what restrictions it has, etc.

So something like:

`:onyx/name`                            [ `:onyx/type` does stuff.
`:onyx/type`  <--- Click -------->   More information.
`:onyx/batch-timeout`                 Cross-reference links]

**Comment by giorgio-v** [comment]
Makes sense. Let’s see if I can come up with something. Not right now, tomorrow I hope (9PM here). Sounds good?

**Comment by MichaelDrogalis** [comment]
No rush, thanks for contributing! :)

**Comment by giorgio-v** [comment]
Hope to be useful.

**Comment by MichaelDrogalis** [comment]
Thanks for how fast everyone moved on this. We have an initial wireframe [up on the website](http://www.onyxplatform.org/cheat-sheet.html). If anyone has designs or work that didn't come up yet, we can still use it - it certainly won't go to waste. This was a good start though! Gonna close this out and open smaller issues to build on this.
