### ISSUE TITLE
Killing all peers results in stuck cluster state

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#273]
Steps to reproduce:
1. Start peers on a particular onyx/id
2. Start a job (possibly unnecessary)
3. Ctrl-c process with peers.
4. Start peers again on same onyx/id

**Comment by MichaelDrogalis** [comment]
I tested this one. The Aeron media driver is surviving after peers are killed with an embedded media driver. It threw `uk.co.real_logic.aeron.driver.exceptions.ActiveDriverException: active driver detected`.

**Comment by MichaelDrogalis** [comment]
The Peer Group inside submit-job collided with the Peer Group on the peers, both running the embedded media driver. Bug confirmed though. The peers come up, but they are never assigned work.

**Comment by lbradstreet** [comment]
I think I also saw this with core.async messaging.

**Comment by lbradstreet** [comment]
I can confirm that this is fixed. Good job.
