### ISSUE TITLE
Validation should check whether task-map's :onyx/min-peers > :onyx/max-peers

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#281]
Currently nothing much happens

**Comment by emidln** [comment]
Should this cause startup to stop and throw or dynamically readjust min-peers to max-peers?

**Comment by MichaelDrogalis** [comment]
This should throw an exception on the call to `onyx.api/submit-job`.

**Comment by MichaelDrogalis** [comment]
Also: this should take place in a Schema check, so code to actually throw an exception should not be part of this patch.

**Comment by lbradstreet** [comment]
Failing validation upon submit-job is good enough (see ns onyx.static.validation). Preferably this would be schema checked in the TaskMap (see onyx.schema), but I don't know of a clean way to do this via prismatic schema.

**Comment by lbradstreet** [comment]
Hah, my email finally sent through, but you said pretty much what I said :)
