### ISSUE TITLE
Plugins may place task metadata in the replica which should be cleaned up

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#284]
The onyx-kafka plugin now places metadata under [:task-metadata job-id task-id]. There isn't really any great way for the plugins to clean this up, as tasks may die, and we can't override or chain log commands. I think [:task-metadata job-id] should be dissoc-in'd when a job is completed.

@MichaelDrogalis?

**Comment by MichaelDrogalis** [comment]
Yes, absolutely. As long as all plugins follow the convention to key their metadata under job-id, and then again under task-id, this is good. Also remember to dissoc on kill and garbage collection.

**Comment by lbradstreet** [comment]
Closed via #287
