### ISSUE TITLE
core-async messaging is no longer required

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#289]
Aeron fits the bill nicely, now that it does connection shortcutting.

Plan for this issue:
1. Switch onyx-template to use Aeron by default (ASAP).
2. Delete core-async messaging.
3. Remove the core.async build run.
4. Add a special, full shortcut build for run on master. Continue with only Aeron/Netty on all other branches (there is a specific test for shortcutting, but it's best if we have a full shortcut build on master)

**Comment by MichaelDrogalis** [comment]
Being worked on in #294.
