### ISSUE TITLE
Flow Condition exception handlers in leaf nodes

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#291]
Currently we don't support handling exceptions in leaf nodes. We should cover this one.

**Comment by MichaelDrogalis** [comment]
Hold on this. `onyx/restart-pred-fn` might be enough to cover this use case.

**Comment by lbradstreet** [comment]
restart-pred-fn is probably ok enough for occasional issues. I'd like to see some extra lifecycles that get called when exceptions are thrown. These would supply the event map to the lifecycle call, plus the exception, and return whether to swallow the exception (it can retry the data if it wants too)

**Comment by MichaelDrogalis** [comment]
@lbradstreet Partial patch for this one [here](https://gist.github.com/MichaelDrogalis/11676e4cd77c08eddefd). This changes the schema, but doesn't pass the test. I think we need to fish around [in this code](https://github.com/onyx-platform/onyx/blob/master/src/onyx/peer/task_lifecycle.clj#L169) to finish it.

**Comment by MichaelDrogalis** [comment]
This was covered in 0.8.4. Closing.
