### ISSUE TITLE
Investigate bug in multiple acknowlegment processes

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#293]
We see this bug crop up in CI very rarely, but it's been around for some time and I'd like to finally nail it.

**Comment by lbradstreet** [comment]
Much desired

**Comment by MichaelDrogalis** [comment]
Haven't seen this one in a very long time. Gonna close.

**Comment by lbradstreet** [comment]
Good call. I've changed messaging enough that it could have been inadvertently fixed by better design.
