### ISSUE TITLE
Switch from Midje to clojure.test

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#296]
It is time. Just grunt work on this one, shouldn't be too hard though.

**Comment by andrewhr** [comment]
YAY!

..ok, nothing against `midje`, but I like how `clojure.test` feels more in line with `test.check` for example. Just curious, have you found some specific issue to want to migrate?

**Comment by MichaelDrogalis** [comment]
Midje was more popular when I started the project. It's less used now, and some of the deps are old.

**Comment by MichaelDrogalis** [comment]
Done.

**Comment by andrewhr** [comment]
@MichaelDrogalis thanks for the rationale!
