### ISSUE TITLE
Create a release checklist 

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#305]
* make sure changes.md are included
* run local perf sanity check using lein test in onyx-benchmark
* long running local benchmark test (overnight). Should pickup potential memory leaks.
* check all builds pass and artifacts release 
* update examples 
* announce on Twitter
* announce on chans
* post on r/clojure
* news.yc if we feel the release is newsworthy enough.
* post on clojure mailing list
* send out newsletter

**Comment by lbradstreet** [comment]
* long running local benchmark test (overnight). Should pickup potential memory leaks.

**Comment by MichaelDrogalis** [comment]
Done.
