### ISSUE TITLE
Add monitoring hook for network bytes written 

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#310]
This should have some way of tracking back to the task that created them (task-id), and should be called after the point of serialisation

**Comment by MichaelDrogalis** [comment]
PR open at https://github.com/onyx-platform/onyx/pull/326. @lbradstreet Can you check that this is emitting the appropriate number of bytes?

**Comment by MichaelDrogalis** [comment]
Added to develop.
