### ISSUE TITLE
Mistake in the windowing docs

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#312]
https://github.com/onyx-platform/onyx/blob/develop/doc/user-guide/windowing.md#onyxwindowingaggregationmin

 :window/aggregation :sum should be :min

**Comment by lbradstreet** [comment]
Actually I think a bunch of them are just copy pastes. We'll clean it up when we finalise the docs anyway.

**Comment by MichaelDrogalis** [comment]
Fixed - my bad.
