### ISSUE TITLE
Discuss method for supplying window aggregation keys

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#313]
```clojure
{:window/id :sum-ages
 :window/task :identity
 :window/type :fixed
 :window/aggregation :sum
 :window/sum-key :age
 :window/window-key :event-time
 :window/range [1 :hour]
 :window/doc "Adds the :age key in all segments in 1 hour fixed windows"}
```
I'm still not sold on supplying `:window/sum-key`. I understand that `:window/window-key` also needs to be supplied, but I think there's a one to one correspondance between a `:window/aggregation` and a need to supply a key for it. Therefore I think it should be:

`:window/aggregation [:sum :age]` in the given doc.

**Comment by MichaelDrogalis** [comment]
Fixed on develop - good call!
