### ISSUE TITLE
User supplied calls which provide functions to handle particular exception types

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#315]
We discussed this in the past. We need a way for users to supply ways to handle exceptions that happen outside of their :onyx/fn - killing the job is often not acceptable in these cases. :restart-pred-fn is helpful but not good enough.

**Comment by lbradstreet** [comment]
@lbradstreet to provide real world examples of these cases.

**Comment by MichaelDrogalis** [comment]
Done!
