### ISSUE TITLE
Making tests using core.async repl refreshable

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#316]
The reliance on core async channels for inputs and outputs makes the tests non-repl refreshable. We either need to switch to memoizing them as in the template or move the stateful defs that use the channels inside the deftest (this works fine - it's slightly ugly but it's just in the tests so I think it's OK).

In the short term I'm happy to just move them inside the tests since it's quick and easy.

**Comment by lbradstreet** [comment]
@MichaelDrogalis

**Comment by lbradstreet** [comment]
This is my preferred approach - it requires minimal transformation of the existing tests.

**Comment by MichaelDrogalis** [comment]
Done, pushed to develop. :)
