### ISSUE TITLE
Default aggregations should aggregate over a key

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#331]
i.e. if you have a segments:
{:name "lucas"}
{:name "john"}

And a counting aggregation and you're using a grouping task with `:onyx/group-by-key :name`, then the state after seeing these segment should be
`{"lucas" 1 "john" 1}`, not `2`.

Work to be performed after #330 is merged.

**Comment by MichaelDrogalis** [comment]
Fixed in develop.
