### ISSUE TITLE
AOT compiled jar causing problems

### ISSUE THREAD

**Issue by Deraen** [onyx-platform/onyx#339]
Hi,

Based on the fact that you are aot compiling `onyx.interop` namespace, I believe the intent of aot compilation is to have some Java classes available in Jar for Java applications?

However, the side effect of AOT is that ALL namespaces that interop namespace transitively depends on are AOT compiled, including clojure.core, timbre, tools.reader... This will cause problems with applications which use need different versions of these dependencies as AOT compiled class files in the classpath will shadow all .clj sources. This completely breaks Clojurescript in project with Onyx dependency.

It should be easy to check what is happening by checking the contents of the jar file.

If the intent of AOT compilation is to provide some Java classes in JAR, I believe the `interop` ns should lazily load other namespaces so that it doesn't have transitive dependencies to other namespaces.

**Comment by lbradstreet** [comment]
Thank you. You are correct that this is the intent, and I was wondering if this would come back to bite us. 

I definitely want to fix this, though I'll have to spend some time looking at the solution and will discuss it with @MichaelDrogalis. We do something similar with the messaging layer, so your solution is not out of the question.

**Comment by nha** [comment]
@lbradstreet Maybe you remember we had a chat about an exception thrown when using ClojureScript, and it turns out this is the reason.
@Deraen thanks for diagnosing the problem and submitting a patch !

**Comment by lbradstreet** [comment]
Oh, great! It was the first thing I thought of when I saw this issue.

I really appreciate you both spending the time to track this down.

**Comment by MichaelDrogalis** [comment]
Thanks for sending in a patch for this @Deraen / @nha. Looking at it now. :)

**Comment by MichaelDrogalis** [comment]
There's not been a whole lot of work around transitive AOT for the last few years. Not sure we have many other options on the table. http://dev.clojure.org/display/design/Transitive+AOT+Compilation

**Comment by MichaelDrogalis** [comment]
Possible fix in c7a08d87e19fffe761aa64063a34f37f022a9e36.

This essentially does the same thing, but elides the costly `require` statement invoked every time. I believe this should work because `onyx.system` will invoke the task lifecycle namespace, which brings on the function namespace that we need. Repeated calls to `resolve`, while non-zero, are relatively small. Thoughts?

**Comment by lbradstreet** [comment]
Assuming it's fixed, I think we should do a new 0.7.x release with just this fix in. I'd hate others to hit this issue over the next month.

**Comment by MichaelDrogalis** [comment]
Agreed. Let's cut one today.

**Comment by MichaelDrogalis** [comment]
@nha & @Deraen: the patch that excludes `require` ended up doing the trick. Thank you both immensely for tracking this down - I've added both of you to the contributors list on the README. Will release today with the fix.
