### ISSUE TITLE
Namespaced Keyword schema checks are overly-aggressive

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#341]
These prevent Java style input plugins from being used.

**Comment by lbradstreet** [comment]
This is done on develop as part of the schema changes, however it still needs to be tested against the benchmark code with java plugin set.

@MichaelDrogalis do you still have the test in onyx-benchmark doing so? If so, could you copy it to a new test and push it up so we can try it out?

**Comment by MichaelDrogalis** [comment]
@lbradstreet Instead of bringing in the end-to-end test, I thought it might be more precise to add tests for the validation portion specifically. We should add Java tests eventually, but I think this might be more helpful for the immediate goal. Let me know if you think otherwise, though.

Done in 8710dc28c051f8c17c27d68e3a664cdec68f738f.

**Comment by MichaelDrogalis** [comment]
Closing, feel free to reopen if you want me to add more tests here.

**Comment by lbradstreet** [comment]
Looks good. I thought that part was actually tested already, as I forgot that the static methods used a non namespaced keyword. I think the logic was to make it natural to Java style, heh.

The main reason I wanted the test in the benchmark code, was so we can sanity check the Java code for benchmark results, but I'm fine with doing it later when we make the Java side code more generally accessible.
