### ISSUE TITLE
Reduce default batch timeout 

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#347]
As discussed with @michaeldrogalis, it will be reduced from 1000ms to 50ms. Should have a corresponding batch-timeout test that adds to the input medium while test is running.

Also try running the whole suite at 1ms.

**Comment by lbradstreet** [comment]
Tests worked fine at 1ms, aside a few that depend on the number of batches read. Thus I have reduced the default timeout to 50ms https://github.com/onyx-platform/onyx/commit/23b2d29e62f5517bd21b0475b75fa4a09d39c2da

**Comment by MichaelDrogalis** [comment]
:+1:
