### ISSUE TITLE
Java 1.8 dependency

### ISSUE THREAD

**Issue by sanel** [onyx-platform/onyx#359]
Looks like Onyx implicitly depends on Java 1.8, since Argona library is compiled with this version. I'm getting:

```
 java.lang.UnsupportedClassVersionError: uk/co/real_logic/agrona/collections/Int2ObjectHashMap : Unsupported major.minor version 52.0
clojure.lang.Compiler$CompilerException: java.lang.UnsupportedClassVersionError: uk/co/real_logic/agrona/collections/Int2ObjectHashMap : Unsupported major.minor version 52.0, compiling:(onyx/messaging/aeron/peer_manager.clj:1:1)
```

when I try to run examples on Java 1.7. Are there any plans to support older Java versions, notable 1.6 and 1.7?

Thanks!

**Comment by lbradstreet** [comment]
Hi @sanel,

Aeron supports Java 1.8+, and we have dropped the other messaging layers as they were requiring too much. We don't have any plans to support earlier versions.

Out of interest, is there any reason you are unable to upgrade to Java 1.8?

Cheers,

Lucas

**Comment by sanel** [comment]
On my dev setup (latest Slackware), official openjdk is 1.7, but I was mostly concerned for my servers (CentOS 6) where I'm planning to evaluate and deploy small Onyx setup. However, I just discovered that RedHat backported openjdk 1.8 so this isn't the issue after all.

Just, I'm feeling better knowing that I'll be able to deploy Onyx on older distros, but if it is an issue to maintain that, I'll try to live with that :)

Thanks for fast reply.

**Comment by MichaelDrogalis** [comment]
We're making an explicit warning for this in 0.8.0, out in the next few weeks: 15795a05102a33c0aa8f7a5bb55554080403c4bb
