### ISSUE TITLE
Consider renaming :onyx/id

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#364]
Possibly to `:onyx/cluster-id`. Placeholder for discussion.

**Comment by MichaelDrogalis** [comment]
This one's ready when we decide to get 0.9.0 cooking.

**Comment by MichaelDrogalis** [comment]
Done in develop. Switch to `:onyx/tenancy-id`.

**Comment by anujsrc** [comment]
@MichaelDrogalis - As per environment cheatsheet- http://www.onyxplatform.org/docs/cheat-sheet/latest/#/env-config - Is ``:onyx/id`` still required if bookkeeper is enabled for v0.9.x onwards?

I see few test usages as well. Kind of confusing-

* https://github.com/onyx-platform/onyx/blob/1cbeb813063135ccff877635d411a0589aa39f4c/test/onyx/scheduler/percentage_multi_job_test.clj#L14
* https://github.com/onyx-platform/onyx/blob/1cbeb813063135ccff877635d411a0589aa39f4c/test/onyx/scheduler/tagged_constraints_test.clj#L179

**Comment by lbradstreet** [comment]
Thanks Anuj. Those are all incorrect. I'll fix them up now. The tests were
side stepping where the tenancy id was used, and only coincidentally
worked. Thanks again.

**Comment by lbradstreet** [comment]
I see what's happening with onyx/id. The cheat sheet is not showing that
onyx/id is deprecated. I thought we had solved this. Thanks for the report!

I've added deprecation information to the cheat sheet as you can see
http://www.onyxplatform.org/docs/cheat-sheet/latest/#peer-config/:onyx/id

**Comment by MichaelDrogalis** [comment]
Whoops -- that was my fault. Thanks for the catch @anujsrc!
