### ISSUE TITLE
Add :onyx/deduplicate? task-map option

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#377]
Allows no uniqueness-key to be set on a windowed-task, in which case it won't deduplicate.

I'm happy to call it something else.

**Comment by MichaelDrogalis** [comment]
I think that's a good name for it.

**Comment by lbradstreet** [comment]
Fixed in https://github.com/onyx-platform/onyx/commit/c1e3b28b32fd54365e276e70494028beb2144464.
