### ISSUE TITLE
Multi-job test failures

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#380]
I noticed a few CI failures for multi job tests, e.g.

FAIL in (log-greedy-job) (greedy_multi_job_test.clj:143)
No peers are executing any tasks
expected: (or (= counts-3 [[0 0] [0 0]]) (= counts-3 [[] []]))
  actual: false

**Comment by MichaelDrogalis** [comment]
Should be fixed with the new scheduler and `get-counts` fix.
