### ISSUE TITLE
Sending a large message breaks Aeron

### ISSUE THREAD

**Issue by prismofeverything** [onyx-platform/onyx#384]
I get the following exception when sending a message that is over the Aeron limit:

`FATAL [onyx.messaging.aeron.publication-manager] - Aeron write from buffer error:  java.lang.IllegalArgumentException: Encoded message exceeds maxMessageLength of 2097152, length=2112492`

Once this happens, the app starts cycling the same tasks over and over again until I kill the process.  Can we either:
- Provide some way to handle this exception?
- Kill the job so that the process does not cycle endlessly and need to be killed?

**Comment by lbradstreet** [comment]
Aeron code says:
@throws IllegalArgumentException if the length is greater than max payload length within an MTU.

So, I think it's probably safe to treat an IllegalArgumentException as such ad kill the job. The problem then is how to do so without any information.

**Comment by lbradstreet** [comment]
I'm considering setting the properties (below) that will mostly close this issue by enabling bigger messages. Benchmark is needed with and without to ensure performance isn't substantially different, depending on which we document one way or the other.

```
                        "-Daeron.mtu.length=16384"
                        "-Daeron.socket.so_sndbuf=2097152"
                        "-Daeron.socket.so_rcvbuf=2097152"
                        "-Daeron.rcv.buffer.length=16384"
                        "-Daeron.rcv.initial.window.length=2097152"
```

**Comment by lbradstreet** [comment]
This is handled much better now that we can split up batches into multiple aeron messages. Thus closing.
