### ISSUE TITLE
Evaluate BtrPlace for more advanced scheduling capabilities

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#392]
http://www.btrplace.org/

Looks pretty good, backed by research papers. 

If it's computationally expensive we may need to switch to a single log follower / per node, where peers subscribe to activity (via a watch on an atom or something), and one thread applies the log entries (and performs the scheduling) and each peer individually performs their actions. This has the added benefit of reducing the number of ZK connections that peers make, which will become a problem over time.

**Comment by MichaelDrogalis** [comment]
@lbradstreet I'll pick this one up after I finish doing targeted testing on the task lifecycle. I did some initial research today - BtrPlace is looking good.

**Comment by MichaelDrogalis** [comment]
Added to develop.
