### ISSUE TITLE
Fix the plugin release process

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#398]
Currently the plugin releases do not update the READMEs which breaks the X.x.x.x releases.

The version should be set back to a snapshot release. 

I'd prefer we always release 4 digit releases of plugins.

For example, if we release 0.8.0, then onyx-metrics 0.8.0.0 should be released, then master should be set to 0.8.0.1-SNAPSHOT with the README and any other files reflecting this.

**Comment by MichaelDrogalis** [comment]
:+1:

**Comment by lbradstreet** [comment]
I think the latest release script in the plugins do this correctly.

From my understanding, unison clones the plugin dirs and then calls their release scripts?

**Comment by MichaelDrogalis** [comment]
Correct.

**Comment by lbradstreet** [comment]
Fixed at alpha4. Woot.
