### ISSUE TITLE
Add keys for windowing and triggers in TestEnv

### ISSUE THREAD

**Issue by gardnervickers** [onyx-platform/onyx#401]
This helper should allow jobs to be created with windowing and triggers
https://github.com/onyx-platform/onyx/blob/5827c22401bcb523d4e97e685c03519803a43964/test/onyx/helper_env.clj#L38-L49

**Comment by gardnervickers** [comment]
It doesn't seem like this is used anymore, maybe I should just pull it into my code?

**Comment by gardnervickers** [comment]
Both 
https://github.com/onyx-platform/onyx/blob/0.8.x/test/onyx/helper_env.clj
and 
https://github.com/onyx-platform/onyx/blob/0.8.x/test/onyx/test_job.clj
define `TestEnv` record and `Manager` protocol.

**Comment by lbradstreet** [comment]
This is a good point. I think we can probably remove it now. I think with-test-env is just as flexible and a lot cleaner.

**Comment by lbradstreet** [comment]
I've removed this code. Please use the helpers in onyx.test-helper and let us know if there's anything missing that you might want.

Thanks for the heads up
