### ISSUE TITLE
Serialize exception that caused kill-job via write-chunk

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#412]
It'd be useful to look up the exception that caused the job to be killed via the dashboard. This shouldn't cause a large increase in data written to ZooKeeper and it can be GC'd.

**Comment by lbradstreet** [comment]
Users should certainly be using exception tracking but that doesn't help correlate the exception to the job very easily.

**Comment by MichaelDrogalis** [comment]
Done for 0.8.3.
