### ISSUE TITLE
Improve performance of acking daemon

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#413]
I think we can use a mutable java HashMap if we make sure the same thread does the garbage collection in between processing acks.

This should improve performance significantly without a big increase in complexity.

**Comment by MichaelDrogalis** [comment]
This would be a good time to start that document about why we do certain things in the name of perf.

**Comment by lbradstreet** [comment]
Agreed. We can add measurements within the document, and then debate whether they're worthwhile given the magnitude of performance. They definitely come with a cost of maintainability.

**Comment by MichaelDrogalis** [comment]
Closing, removed in next release.
