### ISSUE TITLE
Supplied aeron media driver code should use SHARED by default 

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#429]
SHARED mode uses less threads and is less susceptible to dying from resource starvation. I think this should be the default mode for less sophisticated users. More sophisticated users with many cores or who send a lot of data should opt in to DEDICATED mode.

To close this issue, the following should be done:

* Update onyx-template to use this code https://github.com/onyx-platform/onyx-benchmark/blob/master/src/onyx_benchmark/aeron_media_driver.clj which allows mode to be supplied via command line. This code should be modified to default to shared rather than dedicated. Please make changes in this branch https://github.com/onyx-platform/onyx-template/tree/feature/new-idioms/

* Embedded media driver should default to shared. Code should look very similar to the above code https://github.com/onyx-platform/onyx/blob/0.8.x/src/onyx/messaging/aeron.clj#L192

* We should probably allow the mode to be supplied via the peer-config. It's already available via java properties https://github.com/real-logic/Aeron/wiki/Configuration-Options, but I think this is probably important enough for us to define in the peer-config. It will also need to be defined in information_model.cljc and schema.cljc to pass doc_test.clj

**Comment by mushketyk** [comment]
I can take a look at this if no one minds.

**Comment by lbradstreet** [comment]
That would be good. Thanks!

**Comment by lbradstreet** [comment]
Embedded mode now covered by @mushketyk. Thanks!

**Comment by lbradstreet** [comment]
This is now part of the template too. Many thanks to @mushketyk for the help there too.
