### ISSUE TITLE
Create gitbook SUMMARY file

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#433]
I think this is why gitbook builds are failing

**Comment by MichaelDrogalis** [comment]
We've got one here: https://github.com/onyx-platform/onyx/blob/0.8.x/doc/user-guide/SUMMARY.md

Perhaps it's looking for another one in the dev guide.

**Comment by MichaelDrogalis** [comment]
Fixed this by pinning GitBook to a known good version, they have a bug running around causing this error to happen.
