### ISSUE TITLE
Deprecate onyx/batch-timeout, introduce onyx/back-off-policy

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#442]
As discussed a few weeks ago, we can achieve lower latency and higher throughput by not using a timeout, and instead using a back off policy. I think we're ready for this one.

**Comment by lbradstreet** [comment]
Most definitely.

My current preference would be 2+ modes (probably keywords) which have optional arguments (perhaps if used in a vector).

Something like
:shared (low cpu, but use a timeout of a sort) 

:low-latency (burn as much CPU, assume you have a core for this task and you want a batch as soon as possible)

:backoff-policy (similar to aeron's mode, choose back off time between polls, maybe set some maximum timeout as in batch-timeout)

**Comment by lbradstreet** [comment]
Another reason why this should be done: the resolution of core async timeout is only 10ms, which can be pretty substantial if you want to reduce latency in a multi stage pipeline.

**Comment by lbradstreet** [comment]
After the 0.10+ redesign, we stuck with batch-timeout.
