### ISSUE TITLE
Evaluate exponential pending-timeout

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#447]
This could allow more and more time to segments that take a long time in the hope that they would eventually get through/be processed.

It also would allow for more and more time for these segments to progress. 

Also interesting is adaptive max-pending count based on some measure of the timeouts for the currently being processed messages.

**Comment by MichaelDrogalis** [comment]
Pending timeout and pending count will get the axe in ABS, closing.

**Comment by MichaelDrogalis** [comment]
Possibly being implemented before ABS to support particular deployments.

**Comment by lbradstreet** [comment]
No longer relevant in 0.10.
