### ISSUE TITLE
Generatively test flow condition validation logic

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#455]
We could use some help with this one if anyone has a bit of time to spare.

We'd like to have a test.check suite to tighten the semantic validation of flow conditions, seen [here](https://github.com/onyx-platform/onyx/blob/0.8.x/src/onyx/static/validation.clj#L242-L249). I already see at least one bug. It would be great to get better coverage of this entire section.

**Comment by mushketyk** [comment]
Count me in.

Just need some context. What do you mean by "generatrively"? Also do you refer just to functions validate-* like validate-flow-conditions or there are other functions that should be tested?

**Comment by MichaelDrogalis** [comment]
Hi @mushketyk!

By generatively, I'm referring to the set of tests being written with [test.check](https://github.com/clojure/test.check). We often use [test.chuck](https://github.com/gfredericks/test.chuck) for its utilities, too.

In this issue, I'd like to see [`validate-flow-conditions`](https://github.com/onyx-platform/onyx/blob/0.8.x/src/onyx/static/validation.clj#L242) directly tested. That is, we would use test.check generators to create flow conditions that would violate the semantic rules of what flow conditions are allowed to express. The rules are spelled out [in the docs](https://github.com/onyx-platform/onyx/blob/master/doc/user-guide/flow-conditions.md). For example, we'd like to make sure that a flow condition with `:flow/to` set to `:none` is not allowed to proceed a flow condition with `:flow/to` set to `:all`.

**Comment by MichaelDrogalis** [comment]
Came across another bug working in this area: setting `:flow/post-transform` to a value without setting `:flow/exception-thrown?` to `true` doesn't raise any errors. The post-transformation, correctly, does not execute, but the validation logic doesn't stop you from doing this.

**Comment by mushketyk** [comment]
Thank you @MichaelDrogalis !

I'll work on this, but I cannot promise I'll be able to do it quickly since I am new to Clojure :)

**Comment by mushketyk** [comment]
@MichaelDrogalis Would you recommend to write generative tests just for validate-flow-conditions or would it make sense to write some generative tests specifically for separate functions used by validate-flow-conditions, e.g. validate-flow-connections?

**Comment by MichaelDrogalis** [comment]
Let's test it through the main entry function, `validate-flow-conditions`. It has a better chance of catching defects in the long run.

**Comment by mushketyk** [comment]
Hi, I found something that seems like a bug:

```clojure

user=> (def workflow [[:in :proc] [:proc :out]])
#'user/workflow
user=> (def flow [{:flow/from :proc, :flow/to :none, :flow/predicate :abc, :flow/short-circuit? true} {:flow/from :in, :flow/to :all, :flow/predicate :abc, :flow/short-circuit? true}])
#'user/flow
user=> (v/validate-flow-conditions flow workflow)
nil

```

In this flow condition **:flow/to :all** is not the first in the list of flows which violates the constraint described in the documentation.

Is it a bug?

**Comment by mushketyk** [comment]
One more thing. While writing generative tests I see test violations, but I don't see what input caused it. I have a test like:

```clojure

(deftest all-should-be-first-flow-destination
    (checking
      (times 50)
      [sample...]
      ...
          (is (thrown? Exception (v/validate-flow-conditions flow workflow)))
      ...    
          ))) )

```

But when I run it I see the following output in a shell:

```

**Comment by MichaelDrogalis** [comment]
Seems like a bug indeed. :) Good catch!

I've run into the test input display issue before, I worked around it by putting the expectation in a `let` form around it to force evaluation. @lbradstreet have you seen this before?

**Comment by mushketyk** [comment]
Cool! :)
I'll try to fix in my pull request.
BTW. When you detect a bug like this, do you create an isolated (non generative) unit test to cover it or do you still rely on generated tests to catch regressions?

**Comment by MichaelDrogalis** [comment]
A unit test for specific failed cases would be great. Should make regression testing more reliable. Thanks. :)

**Comment by mushketyk** [comment]
I think that I may not have discovered a bug.

**validate-flow-conditions** function currently works as follow: it takes all flow conditions with the same **:flow/from** and checks that among those a condition with ":flow/to" set to **:all** is the first and only one (if it exists).
This means that the following flow conditions are correct, because transition to **:all** is the first transition from **:in** in this vector:

[{:flow/from :proc, :flow/to :out, :flow/predicate :abc}
{:flow/from :in, :flow/to :all, :flow/predicate :abc, :flow/short-circuit? true}]) ; 

While I assumed that all transitions to **:all** should be placed before all other transitions in the vector.

So, did I misread the documentation or **validate-flow-conditions** is incorrect?

**Comment by MichaelDrogalis** [comment]
The perils of reading code on my phone. :)

It seems that the code is correct in this case, and that the documentation is vague. It's an interesting question as to whether or not we should enforce a global ordering of flow conditions across all tasks, rather than just within a single task. I'm inclined to retain the current behavior. As flow conditions are added, it would become a huge pain at resort all other flow conditions. Given that, I think an appropriate fix would be to add a note in the documentation in the Flow Conditions chapter explicitly noting how the semantics are *per* task.

While we didn't find a code bug here, we found a great documentation bug. This is really fantastic work. :)

**Comment by mushketyk** [comment]
Well, this is useful too :) I'll update the documentation when I finish generative tests.

**Comment by MichaelDrogalis** [comment]
The recent tests cover this well. Closing.
