### ISSUE TITLE
Re-enable window crash test

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#458]
@lbradstreet I disabled the intermittently failing assertion until we can look into it. For now I need to make sure the build is green for the specific work I'm doing as I'm pushing a lot of other unrelated patches.

**Comment by MichaelDrogalis** [comment]
Closing, this test wasn't particularly strong to begin with, and it's now being covered by Jepsen.

**Comment by lbradstreet** [comment]
Yup, there are quite a few crash related tests in the plugins that I'd like to get rid of too. They were only a stop gap for our Jepsen work. :+1

**Comment by lbradstreet** [comment]
@MichaelDrogalis
