### ISSUE TITLE
Fix links to examples of peers joining a cluster

### ISSUE THREAD

**Issue by mushketyk** [onyx-platform/onyx#459]
On the following page: https://onyx-platform.gitbooks.io/onyx/content/doc/user-guide/architecture-low-level-design.html

All links to examples of a new peer joining a cluster in section "3-Phase Cluster Join Strategy" are broken.

**Comment by mushketyk** [comment]
Same with examples for peers failure detection.

**Comment by MichaelDrogalis** [comment]
Fixed in 7853530688d2a322f569a9ed01690cf676b68a24. Gitbook has been removed, official docs now live at http://www.onyxplatform.org/docs.
