### ISSUE TITLE
Flow Conditions :flow/from -> :all doesn't catch exceptions

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#464]
The code paths for `:all` skips exception handling.

**Comment by defclass** [comment]
excellent work ! I look forward to fixed version

**Comment by MichaelDrogalis** [comment]
@defclass This fixed and available via Clojars on version `0.8.4-SNAPSHOT`. We're currently withholding an official release due to a small breaking change to triggers that needs to be documented.
