### ISSUE TITLE
Suggest configuration keys using Fuzzy matching

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#467]
See discussion of Elm in Gitter.

**Comment by lbradstreet** [comment]
Some interesting hints docs from the elm compiler https://github.com/elm-lang/elm-compiler/tree/master/hints

Corresponding code for https://cloud.githubusercontent.com/assets/252189/12093827/234d5884-b340-11e5-958e-a5b15eb18708.jpg

I think we should have some more information_model and schema type definitions to help out with this, plus some extra code like levenstein distance.

**Comment by lbradstreet** [comment]
Also worth reading http://elm-lang.org/blog/compilers-as-assistants

**Comment by lbradstreet** [comment]
@dignati, we've been combining the information_model.clj data to good effect with the schema data. I think combining these with the levenstein distance implementation would be a great start. 

Later we could considering match against types/other checks via schema as well as fuzzy name matches to improve the suggestions and show some docs too.

**Comment by dignati** [comment]
Okay great, I can work on this tomorrow.

Lucas Bradstreet <notifications@github.com> schrieb am Mo., 4. Jan. 2016,
21:17:

**Comment by MichaelDrogalis** [comment]
Done in last release.
