### ISSUE TITLE
Java < 8 error message doesn't work for env

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#478]
Reported in https://github.com/onyx-platform/learn-onyx/issues/12.

**Comment by MichaelDrogalis** [comment]
@lbradstreet was right. This got broke when we removed dynamic linking of Aeron and Agrona. This blows up on a simple `require` of `onyx.api`.

**Comment by lbradstreet** [comment]
I don't think I want this badly enough to dynamically load. Dynamic loading can cause problems with AOT anyway, and the error message is not so bad (it warns about incompatible versions at least).

Java users using other platforms would hit similar errors unless they used a loader which performed these before they loaded the main jars.

**Comment by lbradstreet** [comment]
This is one possible solution that works for all but AOT compile. https://github.com/onyx-platform/onyx/pull/486

Anyone using AOT compile should be advanced enough to figure out the error message, as they are probably going into production. I do not believe the trade-off dynamic loading is worth it to make things *slightly* easier for this case. Searches for the error message thrown will quickly find that they are using an incompatible java version.

**Comment by MichaelDrogalis** [comment]
There are too many cases where we'll fail to catch it - and even if we do, as @lbradstreet pointed out, we can get ourselves into more trouble than we bargained for. Closing.
