### ISSUE TITLE
Add dependent projects to release process

### ISSUE THREAD

**Issue by bridgethillyer** [onyx-platform/onyx#487]
- [x] onyx-starter
- [x] onyx-template
- [x] onyx-examples
- [x] onyx-website
- [x] onyx-cheat-sheet
- [x] onyx-plugin-template
- [x] learn-onyx

There may be others, also.

**Comment by lbradstreet** [comment]
onyx-cheat-sheet needs to copy the advanced mode js to the website

**Comment by MichaelDrogalis** [comment]
Updated @bridgethillyer's original post into a list. I added onyx-starter to autorelease.

**Comment by MichaelDrogalis** [comment]
Also picked off learn-onyx.

**Comment by MichaelDrogalis** [comment]
onyx-examples in progress.

**Comment by MichaelDrogalis** [comment]
onyx-examples done.

**Comment by MichaelDrogalis** [comment]
Done, minus the plugin template which will be redone for ABS in the future. Closing out.
