### ISSUE TITLE
Pass in current trigger call opts to trigger sync fn

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#489]
I realise that the trigger sync-fn signature is already quite long. However, it would be useful to know which notification the sync fn is being called as part of.

Potentially we could do either this or https://github.com/onyx-platform/onyx/issues/488 as they overlap somewhat e.g. you have need to be able to parameterize the notifications if your fn can detect which notification it is being called in.

**Comment by MichaelDrogalis** [comment]
This can go in the options map that we added last release. Good change.

**Comment by lbradstreet** [comment]
Closed. Now supplies just the context, not the full trigger opts.
