### ISSUE TITLE
Test trigger changelog updates

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#507]
I can't figure out how these work from the code, so I need to make sure they're outputting the right changelog updates, and whether those updates are properly replayed.

I think for refinement-destructive? they should be setting the window back to the aggregation-init, not to nil.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Recall our conversation from a few months ago about inflating the size of the windows in memory. Nil was used as a value to be explicitly dropped from the window. Using the init state would make the size accrete over time unnecessarily.

**Comment by lbradstreet** [comment]
Ah yes, thanks. That was the idea. 

My main concern is whether we're actually init'ing the aggregation when we replay the log and see a nil, because I don't see anywhere that handles these nils.

Plus, I'm a bit concerned that the number of entries in the log entry isn't correct. Playback assumes that there is an element for each window in the log entry, however iterate-windows only conjes onto the entry if refinement is destructive.

Mostly I don't have a good idea about how it works and this is a reminder to double check it.

**Comment by lbradstreet** [comment]
I believe this was only coincidentally working when the first window had the same id as the first trigger.

Basically when applying the changelog entries you have a list of updates, one for each window, in the same order of the windows
e.g. 
updates: [update-window1 update-window2 update-window3] windows: [window1 window2 window3]

These are then (map list updates windows) and applied together using the corresponding window for the entry.

The trigger log entry is stored in a separate store log entry call
e.g.
[trigger1-update-window1] [trigger2-update-window1]

When this entry is restored, it's mapped over triggers combined with windows, but the window doesn't necessarily correspond to the window in the trigger.

I think we should probably combine the entries into a single entry and a single store-log-entry call. Then when we restore we map over (map list entries (concat windows triggers)) or something like that.

Ultimately I think we should make triggers state machine updates like the aggregations.
Then we can reduce over something like this to do all the state updates:

```clojure
(map list entries (concat (map (juxt :window/id :aggregation/apply-state-fn) windows) 
                                       (map (juxt :trigger/window-id :trigger-compiled/apply-state-fn) triggers))
```

Making the triggers into state machine updates has the added benefit of allowing for more complex state refinements, and possibly even retractions.
