### ISSUE TITLE
Broken links in docs when translated to www.onyxplatform.org

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#508]
e.g.
Aeron Media Driver link on http://www.onyxplatform.org/docs/user-guide/peer-config.html
Windowing link on http://www.onyxplatform.org/docs/user-guide/aggregation-state-management.html

I think we'll need some way to translate these links automatically.

**Comment by lbradstreet** [comment]
Use absolute URLs rather than relative URLs may be enough here.

**Comment by lvh** [comment]
Another example: http://www.onyxplatform.org/docs/user-guide/plugins.html "Pipeline Extensions API"

**Comment by MichaelDrogalis** [comment]
Thanks @lvh -- on it. Will have all these fixed tonight.

**Comment by lvh** [comment]
No rush; just trying to help. Thanks!

**Comment by MichaelDrogalis** [comment]
Always appreciated. :D

**Comment by MichaelDrogalis** [comment]
Fixed all broken links - verified using a dead link checker. :+1:
