### ISSUE TITLE
No longer AOT onyx

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#509]
After the latest Clojure issues, I'm pretty keen to stop AOTing our main library.

What I'd like to do is move onyx.interop to onyx-java, and AOT onyx-java. This would allow java users to implement our interfaces, and still remove all AOT from the clojure library.

I think we could do this pretty simply and automatically given how good our release process is now.

What do you think @MichaelDrogalis?

**Comment by MichaelDrogalis** [comment]
@lbradstreet Sounds good.

**Comment by gigafone** [comment]
I'm only commenting to say "Clojure 1.8" so that searching for this issue is a little easier. :)

**Comment by lbradstreet** [comment]
Error is regarding clojure.lang.Tuple

**Comment by lbradstreet** [comment]
I tried moving onyx.interop to onyx-java. Everything works well, but we now need to require onyx.interop from our peer bootup namespace. "import onyx.interop" from java is not enough.

I'm not sure what the plan should be from here.

**Comment by lbradstreet** [comment]
Maybe we leave the onyx.interop NS in, but only actually AOT it in the onyx-java artifact?

**Comment by lbradstreet** [comment]
Tested this approach, AOT'd in onyx-java. Worked a charm. I think this is how we should proceed.

**Comment by MichaelDrogalis** [comment]
This is fine to me.

**Comment by MichaelDrogalis** [comment]
Released.
