### ISSUE TITLE
Add clojure compatibility test profiles

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#512]
I think it would be enough just to run these when testing on master, and for some limited subset of tests, to make it quick. It's mostly just a smoke test.

**Comment by MichaelDrogalis** [comment]
Done in b99141030f628ddb6ad51ea9d4f5baf719160069 and 966a44b35065f646a1b0e4d77b5591b10f982b63. There are two new profiles for 1.7 and 1.8 - as 1.7 is the minimum that we support. Added a smoke test to run a subset of tests in Clojure 1.8.
