### ISSUE TITLE
Class cast error on rotating filter

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#535]
16-Feb-22 14:24:12 n4 INFO [onyx.state.filter.rocksdb] - Rotating filter bucket after 10000000 elements.
16-Feb-22 14:24:12 n4 FATAL [onyx.state.filter.rocksdb] -
^[[1;31mjava.lang.ClassCastException^[[m: ^[[3m^[[m

**Comment by lbradstreet** [comment]
Fixed this bug.

**Comment by kjothen** [comment]
Hi, I'm running with org.onyxplatform:onyx:0.9.10 and encountered the following related error, which consequently resulted in a fault. I should also point out I am running a tweaked build of onyx, using rocksdbjni:4.9.0... Was the fix applied in 0.9.11?

INFO [onyx.state.filter.rocksdb] - Rotating filter bucket after 10000000 elements.
FATAL [onyx.state.filter.rocksdb] -
                                  java.lang.Thread.run              Thread.java:  745
    java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  617
     java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1142
                                                   ...
                     clojure.core.async/thread-call/fn                async.clj:  439
   onyx.state.filter.rocksdb/start-rotation-thread!/fn              rocksdb.clj:   43
onyx.state.filter.rocksdb/start-rotation-thread!/fn/fn              rocksdb.clj:   46
              onyx.state.filter.rocksdb/rotate-bucket!              rocksdb.clj:   27
                                    clojure.core/swap!                 core.clj: 2261
                                                   ...
                                     clojure.core/conj                 core.clj:   82
java.lang.ClassCastException: org.rocksdb.ColumnFamilyHandle cannot be cast to clojure.lang.IPersistentCollection

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0e00b22c09, pid=16559, tid=139698109236992
#
# JRE version: OpenJDK Runtime Environment (8.0_91-b14) (build 1.8.0_91-b14)
# Java VM: OpenJDK 64-Bit Server VM (25.91-b14 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [librocksdbjni4807157894551346156.so+0x19cc09]  rocksdb::ColumnFamilyData::ColumnFamilyData(unsigned int, std::string const&, rocksdb::Version*, rocksdb::Cache*, rocksdb::WriteBuffer*, rocksdb::ColumnFamilyOptions const&, rocksdb::DBOptions const*, rocksdb::EnvOptions const&, rocksdb::ColumnFamilySet*)+0x89

**Comment by lbradstreet** [comment]
Thank you for the report. I'll look into it shortly.

**Comment by lbradstreet** [comment]
No longer relevant in 0.10.
