### ISSUE TITLE
handle-exception does not apply to exceptions thrown in flow conditions

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#539]
This has come up in the wild. Sometimes you have unrecoverable exceptions in your flow condition predicates, etc and wish for the peers to restart rather than have your job reboot. This issue is not *totally* clear cut, so should discuss whether it's a good idea.

**Comment by MichaelDrogalis** [comment]
Code, test, and docs ready on this one. @lbradstreet

**Comment by MichaelDrogalis** [comment]
Merged.
