### ISSUE TITLE
Messaging documentation links to itself

### ISSUE THREAD

**Issue by lvh** [onyx-platform/onyx#544]
http://www.onyxplatform.org/docs/user-guide/latest/messaging.html

First paragraph:

>  The messaging layer design document can be found at the Messaging section.

... "Messaging" links back to same URL. Not sure if there's a different section or if that was just copied around :)

**Comment by MichaelDrogalis** [comment]
I think we moved this into its own section at some point. Will drop the link, thanks for the report!

**Comment by MichaelDrogalis** [comment]
Fixed in develop, staged for next release.
