### ISSUE TITLE
[ABS] Implement Asynchronous Barrier Snapshotting

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#552]
This issue will be used to track the design and progress of the Asynchronous Barrier Snapshotting algorithm. The work in this issue will replace our current streaming engine - Per-Record processing. This is the same algorithm outlined in [the literature](http://arxiv.org/pdf/1506.08603.pdf), which is itself an iteration of [Chandy/Lamport's work](http://research.microsoft.com/en-us/um/people/lamport/pubs/chandy.pdf).
### Branch

The ABS engine is actively being implemented on the [`abs-engine`](https://github.com/onyx-platform/onyx/tree/abs-engine) branch.
#### Barrier

A barrier is special message that partitions a stream of messages into finite, discrete portion. Barriers indicate progress in terms of execution stages in an input stream. Barriers are artificial and are injected by Onyx itself. Barriers have monotonically increasing identifiers, starting at `0`.
#### Checkpoint

Checkpoints are values that are durably written to stable storage to indicate the progress of a task in a workflow. The checkpoint always includes a barrier ID for which all messages coming before it were acknowledged, and may contain any snapshotted state.
### Design Discussion

This section hashes out the larger pieces of the design and the considerations that need to be taken.
#### Barrier Injection

Barrier messages need to be injected into each input stream at a deterministic location. So far, we believe the easiest way to do that is by injecting a barrier every `N` messages. That is, if we configured Onyx to inject a barrier every `5` messages, an input stream should look exactly like this, every time, even if its replayed by a completely different process:

```
... 17 16 | 15 14 13 12 11 | 10 9 8 7 6 | 5 4 3 2 1
```

The rightmost side of the text indicates the head of the stream, and the leftmost the tail. The pipe (`|`) indicates a barrier. Barriers carry monotonically increasing identifiers _per task_. That is, if there are 3 input tasks, all the first barrier in _each_ task starts at `0`, then proceeds to `1`, and so forth.

The original paper notes:

> Snapshot coordination is implemented as an actor process on the job manager that keeps a global state for an execution graph of a single job. The coordinator periodically injects stage barriers to all sources of the execution graph. Upon reconfiguration, the last glob- ally snapshotted state is restored in the operators from a distributed in-memory persistent storage.

We do not currently see any reason that a central coordinator would inject messages. Given that message streams are processed at different rates, it's unclear how barriers can deterministically be placed into a stream using this approach. Further, processes can pause as they receive such messages from a coordinator. Perfect synchronicity isn't practical to to achieve here.
##### Assumptions
- Every message in an input stream is uniquely identifiable.
- Input streams can be rewinded if there is a downstream failure.
- When a peer writes its checkpoint to durable storage, it must reject its own write if its checkpoint is _lower_ than the checkpoint that exists in storage. This implies that durable checkpoint storage must support CAS.
##### Questions
- Should we allow developers to configure different lengths between barriers for different tasks?
#### Acknowledgment

_Acknowledgement_ is the successful movement of a barrier after it has fully walked the workflow. When a peer executing an output task receives all of its barriers, it messages its upstream input peers about its progress. When an input peer notices that all of its output task peers have reached a new minimum checkpoint, it releases messages from its input medium - effectively marking them as complete, and never eligible for replay.

When a peer boots up into an input task, it reads its last checkpoint from stable storage. The input stream rewinds to that location and begins sending messages downstream.

We need to be careful that when new peers come online, input peers don't expect them to be able to read checkpoints until they are reading any messages at all. We already have a two-phase join process for a peer to start a task. We just need to make sure that we use it. We'll also need to broadcast the `:allocations` key in the cluster per barrier to make sure the cluster configuration hasn't changed.
##### Assumptions
- To survive a fault, an input stream must be able to retain a message even after a process reads that message. The input stream must have an API for the process to explicitly declare that the processing of the message was successful.
#### Ordered message processing

The ABS engine requires that messages be processed in the order that they are sent between two tasks. Some implementations of ABS use a pull-based messaging layer, thus obviates concerns about message reordering. Onyx heavily embraces Aeron, which is a push-based model. Fortunately, for unbroken connections, Aeron guarantees that messages are consumed in the order they are produced for a single stream.
#### Fault Recovery

When a peer comes online for a task, it essentially always moves into fault recovery mode. If the peer is running an input task, it looks up its last checkpoint in stable storage. If no suitable checkpoint is found, it should start the beginning with barrier `0`.

If a downstream peer crashes, a message will be put on the log as normal. Input peers will read this message and rewind the stream to the checkpoint that the peer crashed on and play from there. It's important the before the stream rewinds, the peer emits a barrier to denote that the next set of messages are older. Peers are expected to maintain the current barrier in memory and ignore state-updates for older messages. Stateless transformations should still be applied to pass the message downstream.
#### Backpressure

It's critical that the communication channels between tasks exhibit backpressure. Aeron implements this on our behalf. Producers will spin when writing a message gets a Backpressure return code.
#### Barrier Alignment

Barrier alignment is the process by which a peer waits for all of its upstream tasks to send it a barrier before it itself emits a barrier. We can isolate this algorithm in a component that controls ingress messages.
#### Proposed Design

![abs](https://cloud.githubusercontent.com/assets/918857/13907443/8475b9de-eeab-11e5-8b60-63bec37892d7.png)
##### ABS Streaming Engine Component
- Create a new Component that starts on each virtual peer with the task lifecycle Component.
- The ABS engine component will ultimately pump messages into the task lifecycle component. We want to try and keep all the details of barriers, checkpoints, and fault recovery outside of task lifecycle to keep it simple. The engine will figure out which upstream tasks to read from, when to pause for barrier alignment, and when to emit barriers to downstream tasks. The ABS engine can take messages from its N input core async channels and funnel them back into a single core.async channel from which the task lifecycle will read off of.
- The component in Onyx that reads from Aeron and forwards incoming data onto a set of core.async channels for each peer needs to change. Currently there is one channel for all incoming segments. We need N core.async channels for N immediate upstream tasks. This design aids in implementing barrier alignment. When a barrier is encountered, we want to pause messages coming in from upstream tasks and only read from tasks that haven't given us a barrier yet. Using a core.async channel per upstream tasks forces the producers of those messages to backpressure, which is desired.
- core.async channels must have blocking buffers. They cannot be `sliding` or `dropping` since that would allow message loss, and therefore out of order messages. If messages got out of order, we'd have an indeterminate set of messages between checkpoints.
- Segments cross the wire with their task ID. We can use short task IDs to emit less information, or we can continue to use peer short IDs and do the lookup at the consumer end to figure out which task it came from.
- We need a new message type in our custom protocol to represent a barrier.
- ABS Engine Component should maintain an atom that we'll call the engine state. The engine state contains a mapping from task ID to a set of barrier IDs and peer IDs that have been encountered. As barriers are emitted from this peer, barrier IDs in that map and removed. This is the "pending area" for when we receive a barrier from one task and are waiting for the barriers of other upstream tasks.
- ABS Engine Component works with two main functions:
  - `pick-channels` - function of two parameters *map of task ID -> core.async channel and the engine state) and returns the set of channels that the engine should try to read from. This function isolates the decision of when to pause reading from a channel, and is therefore responsible for implementing barrier alignment.
  - `emit-barrier?` - function of engine state and replica that returns a boolean to denote whether this peer should emit a barrier to its downstream peers after this batch of segments has been processed.
- The ABS engine component should be able shut off barrier alignment via configuration, which degrades to at-least-once message processing.
- The ABS engine should supply a callback function on the ingress channel to the task lifecycle. The callback should be invoked after `write-batch` returns, which will in turn checkpoint to durable storage.
- The ABS engine should supply a `:skip-state-updates?` key on the ingress channel to the task lifecycle. Turning this key on would make the task lifecycle run under "exactly once" semantics.
### Existing Code Changes
- [ ] All plugins need to switch to the `SimpleInput` interface.
- [ ] Rename `SimpleInput` to a more meaningful name.
### New Code-level Additions
- [x] Create a byte protocol for Barrier messages [Patch 7cf7267eb7d2a9fb1e86813f49d2b0c9e2140101]
- [ ] Alter code surrounding Peer Manager to have N channels per upstream task, not one channel
### Code to be removed
- [ ] Acker daemon
- [ ] Peer configuration `:onyx.messaging/ack-daemon-timeout`
- [ ] Peer configuration `:onyx.messaging/ack-daemon-clear-interval`
- [ ] Job key `acker-exclude-inputs`
- [ ] Job key `acker-exclude-outputs`
- [ ] Job key `:acker-percentage`
- [ ] Replica key `ackers`
- [ ] Scheduler constraints for `choose-ackers`
- [ ] ack-ch connecting acking-daemon to task-lifecycle
- [ ] Task-map key `:onyx/pending-timeout`
- [ ] Task-map key `:onyx/max-pending`
- [ ] Task-map key `:onyx/input-retry-timeout`
- [ ] Ack phase of task lifecycle
### Docs to be modified
- [ ] Performance tuning section needs to discuss how ABS works instead of Per-Record.
- [ ] Internal architecture and design will need to be updated. We can take most of the material from this issue and move it into there.
- [ ] Backpressure section needs to remove discussion about buffering messages in-memory at the input site.
### Questions
- Should we tackle iterative computation in this patch?
- Can we get rid of the sentinel in this patch?
- What happens when we have _really_ large barrier IDs because we've been streaming for a long time? We need to wrap around at some point.

**Comment by lbradstreet** [comment]
Done. Iterative computation, and several other features are still missing, but these are being tracked in other issues.
