### ISSUE TITLE
onyx retry when the function sleep above 200 microseconds

### ISSUE THREAD

**Issue by larluo** [onyx-platform/onyx#562]
when i sleep （Thread/sleep 250) in a job and loop the number (range 1 300), it rise to 299 and down to 202.
but the case didn't occur when i adjust the sleep to（Thread/sleep 150).

i need it as i wanna sleep for a short time with some connection, so i want to know whether there is a parameter that can be control the interval.

**Comment by larluo** [comment]
i adjust the onyx/pending-timeout for input, it seems work now

**Comment by MichaelDrogalis** [comment]
@larluo I don't quite follow. Can you explain what exactly you're trying to accomplish?

**Comment by larluo** [comment]
i use the onyx to pull data from restful server and utilize the parallel function.
but the server response need about 1 seconds to complete.
i test it, and find it's the reason the job execution time beyond the normal situation.
<https://github.com/larluo/9now/blob/master/workspace/onyx-eleme/src/onyx_eleme/core.clj>

i'm a newbie to the onyx, so i can't find the related configuration information to adjust it.
and finally i find the onyx/pending-timeout parameter in input plugin source to solve it already.

i also need to use it to land data to hive streaming for backup data(switch from storm, i need to handle the connection exception about hive metastore and retry). so i want to know more about  the execution time configuration.

thanks

**Comment by gardnervickers** [comment]
@larluo Try setting `:onyx/batch-timeout 10000` on your blocking task.

**Comment by MichaelDrogalis** [comment]
@larluo You can read about how Backpressure works [in the docs](http://www.onyxplatform.org/docs/user-guide/latest/backpressure.html).

**Comment by larluo** [comment]
thanks sincerely , i will spend more time on reading the docs and the code.

**Comment by MichaelDrogalis** [comment]
Thanks. Closing for now, reopen if you have questions.
