### ISSUE TITLE
Onyx leaks threads when watching ZooKeeper

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#566]
We've found a thread leak in the following line: https://github.com/onyx-platform/onyx/blob/0.9.x/src/onyx/log/zookeeper.clj#L255

**Comment by lbradstreet** [comment]
@MichaelDrogalis I'm guessing this will be less of an issue with multiplexed connections, but the thread leak will still occur.

**Comment by MichaelDrogalis** [comment]
@lbradstreet Correct.

**Comment by MichaelDrogalis** [comment]
Merged into develop.
