### ISSUE TITLE
Schema check is too restrictive on StateEvent

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#568]
StateEvent checks Event, which doesn't allow keys that aren't present in the Information Model. We need to loosen this to allow user defined keys.

**Comment by lbradstreet** [comment]
I believe this is the right fix, as it actually uses the event map schema, which should already be appropriately loose.

https://github.com/onyx-platform/onyx/commit/04b799bc45ea437359952ea3fefed813e5c05d41

**Comment by lbradstreet** [comment]
Oops, I forgot that there's a bit of a chicken and an egg problem here.
