### ISSUE TITLE
Link "Aeron Media Driver" leads to nowhere.

### ISSUE THREAD

**Issue by rasom** [onyx-platform/onyx#579]
Link "Aeron Media Driver" leads to nowhere in `:onyx.messaging.aeron/embedded-driver?` section of cheat-sheet.
http://www.onyxplatform.org/docs/src/onyx/messaging/aeron_media_driver.clj
<img width="544" alt="2016-04-22 14 13 15" src="https://cloud.githubusercontent.com/assets/2364994/14760562/fb0531ec-094f-11e6-9545-9b84bd68e840.png">

**Comment by MichaelDrogalis** [comment]
Fixed in 523bb8d17dd8f54bbaf946e03a9bb3117e4ee5bc.

**Comment by MichaelDrogalis** [comment]
Staged for next release, thanks for the report!
