### ISSUE TITLE
:trigger/pred arity documentation

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#586]
The docs say

> The signature of :trigger/pred is of arity-5: event, window-id, lower, upper, segment.

Maybe that was the case at some point, but [it isn't now](https://github.com/onyx-platform/onyx/blob/0.9.x/src/onyx/triggers.clj#L73).

**Comment by lbradstreet** [comment]
Thanks for the report. I'll fix the docs.

**Comment by MichaelDrogalis** [comment]
Fixed in 606cab9734fd05a656455b46d88df91363d7684d.
