### ISSUE TITLE
Allow multi-key uniqueness-key

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#590]
I envision something like passing a vector of keywords instead of a single keyword:

```
:onyx/uniqueness-key [:page :position]
```

And internally it would perhaps `juxt` the getter results (as you would do in sorting on multiple keys). This would save having to create an artificial key (i.e. [something that can be used as an argument to `get`](https://github.com/onyx-platform/onyx/blob/686ca2a8bb1fed8cd3a6dbe63d75923460f46888/src/onyx/peer/window_state.clj#L240)) just for windowing needs. However, I'm not sure if this idea creates problems for how this is tracked, but [it looks like it would work](https://github.com/onyx-platform/onyx/blob/cf577d415a9b3f4016cfbf8675fb751a1671bb8d/src/onyx/state/filter/rocksdb.clj#L85)?

**Comment by lbradstreet** [comment]
We already do similar things in group-by-key. Uniqueness-keys may be de-emphasised in future releases which will rely more on the async barrier snapshotting method to ensure aggregations are only performed once per segment.

@MichaelDrogalis, thoughts? I'm OK with adding it for sake of consistency.

**Comment by neverfox** [comment]
Cool. I think I can work up a pull request fairly quickly, if need be. I already have a fork with `process-segment` doing the right thing (with backwards compatibility for single, non-vector keys). It would just need a test or two.

**Comment by MichaelDrogalis** [comment]
I'm good with adding it. Will review when back at my office. Thanks! :)

**Comment by MichaelDrogalis** [comment]
Closed via discussion in #591.
