### ISSUE TITLE
Move monitoring argument into peer-config

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#605]
It's quite awkward to remember to supply the monitoring object as a parameter to every api call e.g. submit-job, await-job-completion, start-peers, etc. I think it'd be simpler to just allow it to be supplied as part of a peer-config i.e. assoc'd in. Then it can be grabbed out from the peer config.

**Comment by MichaelDrogalis** [comment]
Good to me. This is a relatively minor breaking change.

**Comment by drewverlee** [comment]
@lbradstreet This seems to have been done in 07f76dc. https://github.com/onyx-platform/onyx/commit/07f76dc16932829da31331f14b90f21c4405543f

Should this be closed?

**Comment by lbradstreet** [comment]
Yes, this should be closed. thanks!
