### ISSUE TITLE
Improve visibility into job scheduler

### ISSUE THREAD

**Issue by lbradstreet** [onyx-platform/onyx#608]
What I’m thinking is that we output something to timbre under the following conditions:
1. When the submit-job entry is played, but the job that was submitted isn’t scheduled, output a warning.
2. When a job is newly scheduled on reconfigure-cluster-workload, emit a log entry.

**Comment by lbradstreet** [comment]
I think we only need point 1., since there will be lots of starting job log entries when the jobs are scheduled later.

**Comment by MichaelDrogalis** [comment]
Staged into master.
