### ISSUE TITLE
Documentation for :lifecycle/handle-exception incorrect

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#619]
The documentation [here](http://www.onyxplatform.org/docs/user-guide/latest/lifecycles.html) still mentions return values of true or false, as opposed to the correct :kill, :restart, :defer (the cheatsheet gets it right).

**Comment by MichaelDrogalis** [comment]
Fixed in https://github.com/onyx-platform/onyx/commit/56fc864c596f16039bdc79c89b50aee47a7e178a.
