### ISSUE TITLE
Add schema annotation to feedback-exception!

### ISSUE THREAD

**Issue by jcf** [onyx-platform/onyx#629]
If you're being stupid like me this morning you might pass the wrong thing to [`feedback-exception!`](https://github.com/onyx-platform/onyx/blob/28a1d4298d473e7e393e2bffeea3e2b0a1a7bbde/src/onyx/test_helper.clj#L12-L23) and then get some pretty [gnarly errors](https://gist.github.com/jcf/9fcc0c26add7080bbde440e3f3cfe860).

In my case I mistakenly passed the peers rather than the peer config and was told I was not supposed to pass a vector to `onyx.log.zookeeper.Zookeeper/start` thanks to the use of `validate` in that component.

If we can add a schema annotation to `feedback-exception!` to make sure a peer config is passed rather than say the peers themselves that'd be great!

**Comment by MichaelDrogalis** [comment]
Fixed in #630.
