### ISSUE TITLE
[ABS] thoughts on using aggregations as inputs for further processing steps

### ISSUE THREAD

**Issue by aaelony** [onyx-platform/onyx#639]
A suggestion to consider allowing Window aggregations from several/many flow conditions to be re-joined post-aggregation in the same window.

Scenario A:

You have event-level data with many event types (e.g. click-event, purchase-event, email-event, etc..) with different payloads unique to each event, but there are common keys, e.g. user-id, timestamp, etc..., across payloads.  You set up flow-conditions for each of the event types, and again set up windowed aggregates for each grouped on a per user basis.  

So user-id "Bob" has clicked a lot, bought some things, and was emailed a few times.  You compute number of clicks for Bob, the number of times Bob clicks on certain things given some other criteria in the payload (clojure map), and also compute metrics about the purchase-event transactions, how much did Bob spend, how much of SKU-1234 did he buy (all in the purchase-event-payload), and similarly some metrics around the email-event payload.  

So, each event-type has now been processed via a flow-condition for that event-type, and a further aggregation has reduced each event-type to metrics at time-window and user-id level.  

Now it would be great to join the outputs of these aggregates into a new output that effectively constructs a dataset at time-window and user-id level, containing all aggregated metrics (including Bob's).  

Further such a "dataset" output might be analyzed further within Onyx by running some machine learning algorithm to make predictions and serve as a framework for more processing and iteration.

Currently, this might be accomplished by outputing aggregate flows back into Kafka topics to be reconsumed by onyx, but perhaps this flow might be included better in a more integrated manner?

Scenario B:  (simpler)

Compute sums of event level fields (as above), but once you know the totals for the denominators, you wish to add row-percentages and column-percentages.  More generally, you wish to take an aggregate and further aggregate that, and then combine the final results.  This might also be useful for count auditing such that you can programmatically verify that the windowed counts at event level match the windowed counts post-aggregation to user level (from event level to user level) etc...

Thanks for considering these ideas.

Cheers,
Avram

**Comment by gardnervickers** [comment]
@aaelony This is great! The main blocker for this is being actively worked on. I don't think the issue is being updated https://github.com/onyx-platform/onyx/issues/552 anymore but it is a top priority. 

Until then, you're correct that writing to and reading from a durable medium in your trigger functions is the only way to get multiple sequential aggregations in the same job.

**Comment by aaelony** [comment]
Excellent, ABS looks really interesting as well!  Looking forward...

**Comment by lbradstreet** [comment]
Solved in https://github.com/onyx-platform/onyx/commit/cac9702e943b11cdeb1455a5a1fd3ad2587a8426, onyx 0.10.0-beta1.

**Comment by aaelony** [comment]
Wow!  Thanks for all the hard work. amazing.
