### ISSUE TITLE
Triggers firing for all window extents

### ISSUE THREAD

**Issue by JKelly95** [onyx-platform/onyx#640]
Triggers are firing for all window extents, despite setting :trigger/fire-all-extents? to false. In the following code I think you intended to compare :event-type to :new-segment, not :segment.
https://github.com/onyx-platform/onyx/blob/0.9.x/src/onyx/peer/window_state.clj#L141

**Comment by lbradstreet** [comment]
Hi @JKelly95,

Yes, it looks like you're right. Thank you for the report. We'll add a new test, get it fixed up, and cut a new release.

Thanks
