### ISSUE TITLE
Separate flow from other resources in job

### ISSUE THREAD

**Issue by data-empowered** [onyx-platform/onyx#650]
For an interactive data and function scenario, it would help if each segment (or batch of segments) could have their own flow, without creating a new job (as to reduce resources).
I'm using a fixed format, self explainable data format, being rdf triples. Which makes this scenario possible.
(for info see: https://www.w3.org/RDF/)

**Comment by gardnervickers** [comment]
@data-empowered Maybe checkout Flow Conditions for this use case?
http://www.onyxplatform.org/docs/user-guide/0.9.10/#_flow_conditions

**Comment by data-empowered** [comment]
Thank you @gardnervickers. Flow conditions is not really what I'm looking for. @lbradstreet told me to look in to http://www.onyxplatform.org/jekyll/update/2016/06/13/Task-Bundles.html. But it's going to be a week from now, before I can look into this. I'll let you know.

**Comment by lbradstreet** [comment]
Sure. Let us know how you go on the channel. I'm going to close this for now until you have something more concrete.

**Comment by data-empowered** [comment]
Ok, fine with me.
