### ISSUE TITLE
Upgrade rocksdb to support Windows OS

### ISSUE THREAD

**Issue by kjothen** [onyx-platform/onyx#655]
I realize you're not targeting Windows OS, and that's just fine. However, if you were to accommodate the following minor tweaks for rocksdb, then at least you'd be able to use Windows OS for development purposes (albeit, unsupported):
1. Upgrade `[org.rocksdb/rocksdbjni "4.0"]` to `[org.rocksdb/rocksdbjni "4.9.0"]` which contains embedded rocksdb support for Windows OS, and
2. Change `db-dir` in `state-extensions/initialize-filter :rocksdb` from `db-dir (str base-dir-path "/" id "_" task-id)` to `db-dir (str base-dir-path "/" id "_" (name task-id))`, which removes the use of clojure keywords in a Windows OS path name.

**Comment by MichaelDrogalis** [comment]
Cool, we'll check it out. Happy to make those minor changes if it does the trick.

**Comment by lbradstreet** [comment]
We no longer use rocksdb.
