### ISSUE TITLE
Batch function kills job on exceptions

### ISSUE THREAD

**Issue by neverfox** [onyx-platform/onyx#670]
When a batch function experiences an exception, it kills the task (and the job, despite having a task restart lifecycle hook) because it believes you have violated the requirement to return the same number of segments as were contained in the batch.

**Comment by lbradstreet** [comment]
Thanks for the report. I'll look into this today.

**Comment by neverfox** [comment]
I can report that the fix you had me try worked. When can the fix be expected in an official release?

**Comment by lbradstreet** [comment]
I'll get a release out today. Thanks

**Comment by lbradstreet** [comment]
Fixed in 0.9.12
