### ISSUE TITLE
core.async/size isn't used

### ISSUE THREAD

**Issue by jcf** [onyx-platform/onyx#671]
I might be missing something, but it doesn't look like `:core.async/size` is used in the input or output plugin.

``` sh
$ rg ':core\.async/size'
src/onyx/tasks/core_async.clj:                         :core.async/size chan-size
src/onyx/tasks/core_async.clj:                         :core.async/size (inc chan-size)
```

I'd expect to see `:core.async/size` being referred to in `onyx.plugin.core-async`, maybe?

**Comment by lbradstreet** [comment]
You are correct, and I had thought I had already pushed a fix for this, however it appears to have been lost somewhere. Thanks for the report.

**Comment by jcf** [comment]
Thanks, @lbradstreet. I'm patching in my app now.

Want me to put together a PR that fixes this upsteam?

**Comment by lbradstreet** [comment]
core.async/size is used in the lifecycle functions.
