### ISSUE TITLE
Evict idle grouped window aggregation

### ISSUE THREAD

**Issue by yonatane** [onyx-platform/onyx#696]
In a scenario where a global grouped window was created due to some segments but then wasn't needed anymore, it would be beneficial to have some eviction policy to clean it from RAM at least.
A concrete example for this case is a CQRS short lived aggregate that doesn't process more than a few commands and then only needed in durable storage.

**Comment by MichaelDrogalis** [comment]
Refinement modes should be modified to clear away group contents and their markers in the aggregation state when a discarding refinement is used. Another policy here is not unwarranted.

**Comment by lbradstreet** [comment]
Fixed when eviction was implemented in a previous release.
