### ISSUE TITLE
Namespaced keyword as task name fails RocksDB

### ISSUE THREAD

**Issue by yonatane** [onyx-platform/onyx#699]
When naming a task with a namespaced keyword (e.g :my.ns/processor), it causes an error:
`org.rocksdb.RocksDBException: IO error: /tmp/rocksdb_filter/e268acd9-2230-48b6-b79c-2dfd74c86bed_:my.ns/processor: No such file or directory`

Task name is used as is in the path which causes the error.

**Comment by MichaelDrogalis** [comment]
Closing, RocksDB is gone in 0.10.
