### ISSUE TITLE
allowing joins in query selections

### ISSUE THREAD

**Issue by blueneogeo** [onyx-platform/onyx#741]
I was trying out the .select that returns a Map<String, ?> instead of a List<T>. I think I understand now how it works, once I set the select property on a query, it will return me a list of maps of attribute_name ->  value, with an attribute for each selected attribute.

I had actually expected this feature to work differently. I thought originally that select would still return a List<IManagedEntity>, but that it would only hydrate those selected fields.

Then I figured out that it returns a map, and I thought it would allow us to query relationship values as well, outside an entity. However that does not seem to be the case. If I try to select outside the entity, it will return null.

My suggestion is, either have select in a normal query still to return entities, but just only hydrate the fields that you selected, and / or  make select more powerful and allow to query joins as well. For example:

Lets say we have a Person with each having a single Address. Address has a relationship with Person as a List<Address> occupants. So multiple persons can live at a single address.

What I expect to happen is that I can do this:

``` xtend
query.setSelections(“firstName”, “address.street”)
```

and then to get this result (if I put the list<map> in a json like format:

```javascript
var result = [
 {
  “firstName” : “Pascal”,
  “address.street”: “Sluisvaart"
 }
]
```

Or, if I select this:

```xtend
query.setSelections(“firstName”, “address”)
```

and then to get this result (if I put the list<map> in a json like format:

```javascript
var result = [
 {
  “firstName” : “Pascal”,
  “address”: {
   “street”: “Sluisvaart”,
   “houseNr”: 98
  }
 }
]
```

**Comment by MichaelDrogalis** [comment]
You've got the wrong Onyx project. Closing.
