### ISSUE TITLE
Adding QueryCriteria.not()

### ISSUE THREAD

**Issue by blueneogeo** [onyx-platform/onyx#742]
Suggestion is to add QueryCriteria.not() which returns a new QueryCriteria that is the inverse of the original.

This would allow a more generic solution to NOT_NULL or NOT_IN etc, in that it allows you to work with combined criteria as well. This lets you eliminate the NOT_NULL and NOT_IN etc.

An example:

```xtend
val isOldEnough = new QueryCriteria(“age”, GREATER_THAN, 18)
val canDrive = new QueryCriteria(“hasDrivingSkills”, EQUALS, true)
val mayHaveLicense = isOldEnough.and(canDrive)
val mayNotHaveLicense = mayHaveLicense.not()
```

Of course I could rewrite the criteria to make this work as well, but this can get harder with more complicated compound queries, so I think this makes sense. 

In DSLs like Xtend-onyx, , it will allow overloading the ! operator:

```xtend
val unqualifiedDrivers = db.query(Driver.Data)
   .where [ !(age > 18 && canDrive == true) ]
   .list
```

**Comment by MichaelDrogalis** [comment]
You've got the wrong Onyx project. Closing.
