### ISSUE TITLE
Error running lein test in onyx-starter on windows 7

### ISSUE THREAD

**Issue by jburvill** [onyx-platform/onyx#765]
Got the below error on windows. Works fine on ubuntu.

Deleting the mentioned aeron folder didn't help.

java.nio.file.FileSystemException: C:\Users\t460\AppData\Local\Temp\aeron-t460\cnc.dat: The process cannot access the file because it is being used by another process.
[onyx-starter-error.txt](https://github.com/onyx-platform/onyx/files/973395/onyx-starter-error.txt)

**Comment by MichaelDrogalis** [comment]
@jburvill Onyx isn't supported under Windows, so I can't really diagnose what's going on here. Sorry. :(
