### ISSUE TITLE
Can we coordinate one or more processor topologies?

### ISSUE THREAD

**Issue by twashing** [onyx-platform/onyx#778]
Question. In the [user guide](http://www.onyxplatform.org/docs/user-guide/0.10.x/#concepts), [onyx-examples](https://github.com/onyx-platform/onyx-examples) and [learn-onyx](https://github.com/onyx-platform/learn-onyx) projects, all the workflows end in an output. 

But I'm looking to build a set of microservices that are connected by kafka topics (see [here](https://drive.google.com/file/d/0B213_8Py7z1AVFpBRlFtd0FFUXM/view?usp=sharing)). 

**A)** Is there an example where the output topic of one microservice, is the input to another? Or is a single workflow only meant to be run on 1 machine? The analogy I'm thinking of, is Kafka Streams' one or more [processor topologies](https://kafka.apache.org/documentation/streams#streams_concepts). I have a feeling that there's a pattern around flow conditions. But that all seems to happen on the same machine, in the sample workflow. And I don't see where we can inject intermediate topics between processing functions. 

If a single workflow is only meant to be run on 1 machine, then can workflows on several machines join the same [cluster](http://www.onyxplatform.org/docs/user-guide/0.10.x/#_joining_the_cluster)? Ie, can an "application" span several machines? If so how do we coordinate between several workflows, executing on separate machines?

**B)** And tangentially, in our code or configuration, do we need to think about how to coordinate segments from a topic that has 1 partition, to a topic with n partitions?

**Comment by MichaelDrogalis** [comment]
Your mental model of how Onyx works is a little off. I'll try to summarize and then suggest an approach to what you're doing.

It sounds like you're coming from the Kafka Streams where, where a single unit of work is deployed and executed locally on one machine in the form of a Kafka consumer. Kafka Streams scales the amount of work you can perform by pinning more consumer groups to a single topic, thus fanning out the work on your behalf. The effect is that messages are distributed, but the work is performed entirely on a single machine.

Onyx, on the other hand, uses the notion of a workflow to denote units of work that are executed across different machines, and independently scalable. If you have a workflow with tasks A, B, and C, and a cluster of machines with 60 peers (say 20 peers per machine), each task can get 20-way parallelism, sending messages between different machines. In this way, you get concurrency and parallelism every step of the way. As you add more peers, you can consume from Kafka with more parallelism. A workflow is a fully distributed topology in its own right, and if you add more machines to those examples, you'll see the work automatically fanned out across the cluster.

For a single cluster, you can deploy as many workflows (or, more properly called jobs) as your resources allow. The different schedulers will take advantage of your peers in different ways for increased parallelism, preferred priority, and so forth.

Regarding chaining jobs together - what's most typical to design streaming architectures as unidirectional data flow systems. That is, each workflow would have a Kafka input and, most likely, a Kafka output, where each job in succession is writing to the next Kafka topic.

How you approach it further is heavily application dependent. I can advise further if needed, but hopefully that helps you understand how Onyx works a bit better. 

Regarding (B) - it depends. There's nothing "special" that needs to be done to handle it. Onyx will fan the work out, and depending on what key partitioner you use for Kafka, Onyx will slot it into the appropriate partition. So long as you can hint which partition a message should go into, everything is taken care of from what point on. The reader task especially will be automatically parallelized read from whichever partitions are requested.

**Comment by twashing** [comment]
Right, so you can deploy many workflows (or jobs) to the same cluster. That makes sense, especially if each workflow has a kafka input and output, and kafka topics are sitting between those workflows.

So it really just looks as simple as running `(onyx.api/submit-job peer-config job)` for each workflow you want to run. They just all have to point to the same cluster, via `:onyx/tenancy-id`.

I just need to figure out if that's all that's needed across several machines. Ie, do I have to coordinate these calls. 
```
(onyx.api/start-env env-config)
(onyx.api/start-peer-group peer-config)
(onyx.api/start-peers peer-count peer-group)
```

But that otherwise clarifies things for me. Thanks once again.

**Comment by MichaelDrogalis** [comment]
> So it really just looks as simple as running (onyx.api/submit-job peer-config job) for each workflow you want to run. They just all have to point to the same cluster, via :onyx/tenancy-id.

Exactly.

> I just need to figure out if that's all that's needed across several machines. Ie, do I have to coordinate these calls.

These calls are run once on every machine you wish to participate in the Onyx cluster. It's simply bringing the peer online. All you need to do is call `submit-job` for each of your jobs, presumably from somewhere outside the cluster. All that does is serialize the Onyx job data structure to ZooKeeper. The peers automatically fan out the work amongst themselves.

**Comment by twashing** [comment]
Sweet. Thanks Michael. 👍
