### ISSUE TITLE
Avoid WARNINGs for clojure 1.9 alpha programs

### ISSUE THREAD

**Issue by kjothen** [onyx-platform/onyx#792]
I find that onyx + clojure.spec combine nicely together, mainly using spec to coerce raw segment data from one format to another, eg from csv to datomic. There is one annoyance when using clojure 1.9 alphas with onyx though: the warnings below are written to the log at the start of every onyx job. I think the first warning is [fixed](https://github.com/plumatic/schema/blob/master/CHANGELOG.md) in plumatic/schema from version 1.1.2, so do you think you could bump the onyx version from 1.0.5?
```
WARNING: Inst already refers to: #'clojure.core/Inst in namespace: schema.core, being replaced by: #'schema.core/Inst
WARNING: any? already refers to: #'clojure.core/any? in namespace: clj-fuzzy.helpers, being replaced by: #'clj-fuzzy.helpers/any?
```
As for the second, in clj-fuzzy, not so sure what the strategy should be here.

**Comment by MichaelDrogalis** [comment]
Can definitely bump Schema. I'll do that now on develop, thanks!

**Comment by MichaelDrogalis** [comment]
Schema upgraded via https://github.com/onyx-platform/onyx/commit/96d0823739f2de42391a6d25460dba8c02c0a55d.

**Comment by MichaelDrogalis** [comment]
Out on last release.
