### ISSUE TITLE
user-guide on 0.11.x is not up to date

### ISSUE THREAD

**Issue by eriktjacobsen** [onyx-platform/onyx#806]
In looking over the release notes, these seem to be missing from the guide:

> BREAKING CHANGE :onyx.refinements/discarding and :onyx.refinements/accumulating have been removed. To retain current behaviour, use :trigger/post-evictor :all
BREAKING CHANGE :aggregation/create-state-update fn signature has changed from (window, state, segment) to (window, segment). achieve discarding behaviour, and delete the refinement to achieve accumulating behaviour as the accumulating refinement did nothing.
:trigger/post-evictor has been added, which improves window cleanup for flushed window extents.

**Comment by lbradstreet** [comment]
Thank you. I will update it. We’ve been treating the cheat sheet as the authoritative source, but I still need to update the guide. Thanks!
