### ISSUE TITLE
java.io.FileReader cannot be cast to java.io.BufferedReader

### ISSUE THREAD

**Issue by halcyon** [onyx-platform/onyx#812]
When  using `onyx.tasks.seq/input-file`  a ClassCastException is thrown at the end of the job. 

java.lang.ClassCastException: java.io.FileReader cannot be cast to java.io.BufferedReader
      function: #<Var@5497a81a: 
                  #function[com.stuartsierra.component/eval29424/fn--29436/G--29415--29441]>
        reason: :com.stuartsierra.component/component-function-threw-exception
        system: #<Onyx Task>
    system-key: :task-lifecycle

**Comment by lbradstreet** [comment]
Merged and closing the issue. Thanks again.
