### ISSUE TITLE
Arity exception when using colocated task scheduler

### ISSUE THREAD

**Issue by eelkevanfoeken** [onyx-platform/onyx#823]
When using onyx 0.11 I see that when using the colocated scheduler there occurs an arity exception because here https://github.com/onyx-platform/onyx/blob/0.11.x/src/onyx/scheduling/colocated_task_scheduler.clj#L11 the `get-peer-site` function is called with one too many arguments

**Comment by lbradstreet** [comment]
Thank you for this report. I will get onto this soon.

**Comment by lbradstreet** [comment]
Thanks, fixed. We will be releasing onyx 0.12 with this fix shortly.
