### ISSUE TITLE
Typo in User Guide pictures (ABS Execution Example)

### ISSUE THREAD

**Issue by malesch** [onyx-platform/onyx#833]
In the [ABS Execution Example](http://www.onyxplatform.org/docs/user-guide/0.12.x/#_abs_execution_example), Step 3, the peer `:input2` is mentioned but which does not exist in the diagram. If my understanding is correct the lower input box should be denoted `:input2`. This input peer label also appears in the description for the snapshot of `:input2`.

![step3](https://user-images.githubusercontent.com/114063/33882747-7519a312-df39-11e7-843f-7314ff550d8f.png)

**Comment by lbradstreet** [comment]
Thank you, you are correct. I will fix this up.

**Comment by lbradstreet** [comment]
Fixed in master. Thanks again.
