### ISSUE TITLE
Is Dire still used in Onyx platform?

### ISSUE THREAD

**Issue by piotr-yuxuan** [onyx-platform/onyx#852]
Hi there,
Thanks for this amazing project which looks so appealing!

At the beginning of the [user guide](https://github.com/onyx-platform/onyx/blob/7903b6dd459c4b0a45b97ca1705fed06ebd07e4d/doc/user-guide/what-does-it-offer.adoc#aspect-orientation) you talk about Dire:

> Clojure functions again serve as a huge win. [Dire](https://github.com/MichaelDrogalis/dire) is a library that supports aspects, meaning you can keep your application logic airtight away from logging, preconditions, and error handling.

However it seems to be the [sole occurrence](https://github.com/onyx-platform/onyx/search?utf8=%E2%9C%93&q=dire&type=) of the term in this project as a whole; moreover [Dire](https://github.com/MichaelDrogalis/dire) project itself has been archived. Any feedback on it?

**Comment by Atsman** [comment]
@piotr-yuxuan i had the same question in my head, while reading documentation

**Comment by gardnervickers** [comment]
No it is not used. We should probably remove that from the user guide.

**Comment by Atsman** [comment]
@piotr-yuxuan will u do that?

**Comment by piotr-yuxuan** [comment]
Yeah, sure!

**Comment by piotr-yuxuan** [comment]
Gonna read through the user guide for small stuff like this one.

**Comment by Atsman** [comment]
@piotr-yuxuan cool!

**Comment by piotr-yuxuan** [comment]
Closing, as `dire` is removed.
