### ISSUE TITLE
Predicate job and task scheduler

### ISSUE THREAD

**Issue by MichaelDrogalis** [onyx-platform/onyx#94]
Support new job schedulers that dispatch based off of arbitrary user functions and data. Motivation is to support Datomic peers without blowing the cap.

**Comment by lbradstreet** [comment]
This is nice, but it's worth leaving for 0.6.1 unless you think it's really easy. I think the priority should be allowing people to get away from HornetQ.

**Comment by MichaelDrogalis** [comment]
Keeping priorities in check. :+1:

**Comment by lbradstreet** [comment]
Somebody has to make sure we don't miss out on those stickers :tada:

**Comment by MichaelDrogalis** [comment]
Closing in favor of the new Constraints feature.
